///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CSP.AmazonS3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The S3WorkFlow recording.
    /// </summary>
    [TestModule("905f74ae-8e48-4eb5-877d-78231d4eb473", ModuleType.Recording, 1)]
    public partial class S3WorkFlow : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::CSP.CSPRepository repository.
        /// </summary>
        public static global::CSP.CSPRepository repo = global::CSP.CSPRepository.Instance;

        static S3WorkFlow instance = new S3WorkFlow();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public S3WorkFlow()
        {
            AuthToken = "IgOgdLNEAzGEjvyONsrg1tgK2SSCu-8axAr8WOF52erGxL9SEyBZ7krKrwub3Wyp";
            studyProtocolName = "AutomationStudy";
            DOM = "cgst-qc-orr.azurewebsites.net";
            dob = "2000-01-01";
            genderCode = "m";
            localityCode = "en_US";
            redirectError = "WWW.GOOGLE.COM";
            redirect = "www.facebook.com";
            visitSessionCode = "visit1";
            supervisorId = "1";
            TestIdentifier = "";
            externalId = "";
            AssessmentURL = "";
            mode = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static S3WorkFlow Instance
        {
            get { return instance; }
        }

#region Variables

        string _AuthToken;

        /// <summary>
        /// Gets or sets the value of variable AuthToken.
        /// </summary>
        [TestVariable("08c0fb6e-58a5-47ed-adeb-457de1f0ae40")]
        public string AuthToken
        {
            get { return _AuthToken; }
            set { _AuthToken = value; }
        }

        string _studyProtocolName;

        /// <summary>
        /// Gets or sets the value of variable studyProtocolName.
        /// </summary>
        [TestVariable("e380e8ca-b696-4acb-b05d-ae29d35045d9")]
        public string studyProtocolName
        {
            get { return _studyProtocolName; }
            set { _studyProtocolName = value; }
        }

        string _DOM;

        /// <summary>
        /// Gets or sets the value of variable DOM.
        /// </summary>
        [TestVariable("40353c7d-ac31-4cee-af78-a966f72d1c73")]
        public string DOM
        {
            get { return _DOM; }
            set { _DOM = value; }
        }

        string _dob;

        /// <summary>
        /// Gets or sets the value of variable dob.
        /// </summary>
        [TestVariable("2014aaa3-d5ca-4c6a-a508-b19e9c08ed38")]
        public string dob
        {
            get { return _dob; }
            set { _dob = value; }
        }

        string _genderCode;

        /// <summary>
        /// Gets or sets the value of variable genderCode.
        /// </summary>
        [TestVariable("0d080b8c-e98c-4347-9679-76db4a2a81d1")]
        public string genderCode
        {
            get { return _genderCode; }
            set { _genderCode = value; }
        }

        string _localityCode;

        /// <summary>
        /// Gets or sets the value of variable localityCode.
        /// </summary>
        [TestVariable("37f149fb-6f81-4493-9749-7e13d8b5c33b")]
        public string localityCode
        {
            get { return _localityCode; }
            set { _localityCode = value; }
        }

        string _redirectError;

        /// <summary>
        /// Gets or sets the value of variable redirectError.
        /// </summary>
        [TestVariable("9a947344-3a37-4c89-9e60-da448fabab8f")]
        public string redirectError
        {
            get { return _redirectError; }
            set { _redirectError = value; }
        }

        string _redirect;

        /// <summary>
        /// Gets or sets the value of variable redirect.
        /// </summary>
        [TestVariable("30f37748-e987-43b8-861d-9d4df2f5455e")]
        public string redirect
        {
            get { return _redirect; }
            set { _redirect = value; }
        }

        string _visitSessionCode;

        /// <summary>
        /// Gets or sets the value of variable visitSessionCode.
        /// </summary>
        [TestVariable("9309939c-db47-423b-bbdd-d7fb84361d3a")]
        public string visitSessionCode
        {
            get { return _visitSessionCode; }
            set { _visitSessionCode = value; }
        }

        string _supervisorId;

        /// <summary>
        /// Gets or sets the value of variable supervisorId.
        /// </summary>
        [TestVariable("45ecc239-8ba6-4ceb-8d91-2a71ac6ab937")]
        public string supervisorId
        {
            get { return _supervisorId; }
            set { _supervisorId = value; }
        }

        string _TestIdentifier;

        /// <summary>
        /// Gets or sets the value of variable TestIdentifier.
        /// </summary>
        [TestVariable("37e291cb-355e-4582-909a-9dde892ff08d")]
        public string TestIdentifier
        {
            get { return _TestIdentifier; }
            set { _TestIdentifier = value; }
        }

        string _externalId;

        /// <summary>
        /// Gets or sets the value of variable externalId.
        /// </summary>
        [TestVariable("c9f808a3-6e8a-4420-abfc-bf605bd6f28a")]
        public string externalId
        {
            get { return _externalId; }
            set { _externalId = value; }
        }

        string _AssessmentURL;

        /// <summary>
        /// Gets or sets the value of variable AssessmentURL.
        /// </summary>
        [TestVariable("d24a23f2-af13-4830-83f1-63d953518a04")]
        public string AssessmentURL
        {
            get { return _AssessmentURL; }
            set { _AssessmentURL = value; }
        }

        string _mode;

        /// <summary>
        /// Gets or sets the value of variable mode.
        /// </summary>
        [TestVariable("3e9fbba9-def8-4e70-8ad5-ebbf204e5b18")]
        public string mode
        {
            get { return _mode; }
            set { _mode = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            GenerateWF(AuthToken, studyProtocolName, DOM, dob, genderCode, localityCode, redirectError, redirect, mode);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
