///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CSP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The emptyassement recording.
    /// </summary>
    [TestModule("85b942bb-b28e-4f71-9de0-2146ec915b8b", ModuleType.Recording, 1)]
    public partial class emptyassement : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CSPRepository repository.
        /// </summary>
        public static CSPRepository repo = CSPRepository.Instance;

        static emptyassement instance = new emptyassement();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public emptyassement()
        {
            workflowID = "";
            DOM = "";
            workflowToken = "";
            Batteryid = "";
            B_id = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static emptyassement Instance
        {
            get { return instance; }
        }

#region Variables

        string _workflowID;

        /// <summary>
        /// Gets or sets the value of variable workflowID.
        /// </summary>
        [TestVariable("10e679a8-0397-4670-b1f5-e83f73725ebc")]
        public string workflowID
        {
            get { return _workflowID; }
            set { _workflowID = value; }
        }

        string _DOM;

        /// <summary>
        /// Gets or sets the value of variable DOM.
        /// </summary>
        [TestVariable("5699390c-f92e-473f-b8e1-bc4c097ae37c")]
        public string DOM
        {
            get { return _DOM; }
            set { _DOM = value; }
        }

        string _workflowToken;

        /// <summary>
        /// Gets or sets the value of variable workflowToken.
        /// </summary>
        [TestVariable("c94deacb-278f-4411-ae91-cebbf1607434")]
        public string workflowToken
        {
            get { return _workflowToken; }
            set { _workflowToken = value; }
        }

        string _Batteryid;

        /// <summary>
        /// Gets or sets the value of variable Batteryid.
        /// </summary>
        [TestVariable("24d34ef6-f8db-428d-8bc3-8da0240e6fd2")]
        public string Batteryid
        {
            get { return _Batteryid; }
            set { _Batteryid = value; }
        }

        string _B_id;

        /// <summary>
        /// Gets or sets the value of variable B_id.
        /// </summary>
        [TestVariable("f3368836-8e52-4a99-af16-b0555f9a06d0")]
        public string B_id
        {
            get { return _B_id; }
            set { _B_id = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            E_mptyAssment(workflowID, DOM, workflowToken, Batteryid);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
