///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CSP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GetBatteryAssessee recording.
    /// </summary>
    [TestModule("d047df37-f87c-45bf-9e45-0756caa1dca2", ModuleType.Recording, 1)]
    public partial class GetBatteryAssessee : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CSPRepository repository.
        /// </summary>
        public static CSPRepository repo = CSPRepository.Instance;

        static GetBatteryAssessee instance = new GetBatteryAssessee();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GetBatteryAssessee()
        {
            workflowID = "";
            DOM = "";
            workflowToken = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GetBatteryAssessee Instance
        {
            get { return instance; }
        }

#region Variables

        string _workflowID;

        /// <summary>
        /// Gets or sets the value of variable workflowID.
        /// </summary>
        [TestVariable("15ba03e8-a284-454b-a82c-bdb793e3e354")]
        public string workflowID
        {
            get { return _workflowID; }
            set { _workflowID = value; }
        }

        string _DOM;

        /// <summary>
        /// Gets or sets the value of variable DOM.
        /// </summary>
        [TestVariable("fd0a4671-4181-418f-a788-9469d601f468")]
        public string DOM
        {
            get { return _DOM; }
            set { _DOM = value; }
        }

        string _workflowToken;

        /// <summary>
        /// Gets or sets the value of variable workflowToken.
        /// </summary>
        [TestVariable("445f5774-7b30-4d27-9759-2ac5dbc10b96")]
        public string workflowToken
        {
            get { return _workflowToken; }
            set { _workflowToken = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Get_BatteryAssessee(workflowID, DOM, workflowToken);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
