///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CSP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The IAMusername recording.
    /// </summary>
    [TestModule("807c2d98-ddb1-4b14-bae3-47b9dee0d191", ModuleType.Recording, 1)]
    public partial class IAMusername : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CSPRepository repository.
        /// </summary>
        public static CSPRepository repo = CSPRepository.Instance;

        static IAMusername instance = new IAMusername();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public IAMusername()
        {
            Imusername = "cgstqcuser";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static IAMusername Instance
        {
            get { return instance; }
        }

#region Variables

        string _Imusername;

        /// <summary>
        /// Gets or sets the value of variable Imusername.
        /// </summary>
        [TestVariable("8038b9d3-d0f4-4d72-a383-2a99cacf8e7e")]
        public string Imusername
        {
            get { return _Imusername; }
            set { _Imusername = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(0));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Home}{LShiftKey down}{End}{LShiftKey up}{Delete}' with focus on 'AmazonWebServicesSignIn.IAMusername'.", repo.AmazonWebServicesSignIn.IAMusernameInfo, new RecordItemIndex(1));
            repo.AmazonWebServicesSignIn.IAMusername.PressKeys("{Home}{LShiftKey down}{End}{LShiftKey up}{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(2));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Imusername' with focus on 'AmazonWebServicesSignIn.IAMusername'.", repo.AmazonWebServicesSignIn.IAMusernameInfo, new RecordItemIndex(3));
            repo.AmazonWebServicesSignIn.IAMusername.PressKeys(Imusername);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
