///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CSP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RrunWorkflow recording.
    /// </summary>
    [TestModule("957128ba-5359-452d-b0db-ee9e12c48683", ModuleType.Recording, 1)]
    public partial class RrunWorkflow : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CSPRepository repository.
        /// </summary>
        public static CSPRepository repo = CSPRepository.Instance;

        static RrunWorkflow instance = new RrunWorkflow();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RrunWorkflow()
        {
            authoToken = "";
            studyProtocolName = "";
            DOM = "";
            genderCode = "";
            localityCode = "";
            postError = "";
            post = "";
            visitSessionCode = "";
            supervisorid = "";
            TestIdentifier = "";
            externalid = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RrunWorkflow Instance
        {
            get { return instance; }
        }

#region Variables

        string _authoToken;

        /// <summary>
        /// Gets or sets the value of variable authoToken.
        /// </summary>
        [TestVariable("2599e18e-a4cd-46b0-a2a5-73a913741fd7")]
        public string authoToken
        {
            get { return _authoToken; }
            set { _authoToken = value; }
        }

        string _studyProtocolName;

        /// <summary>
        /// Gets or sets the value of variable studyProtocolName.
        /// </summary>
        [TestVariable("beb0ba57-043e-44e6-8f04-d74da9be6c7a")]
        public string studyProtocolName
        {
            get { return _studyProtocolName; }
            set { _studyProtocolName = value; }
        }

        string _DOM;

        /// <summary>
        /// Gets or sets the value of variable DOM.
        /// </summary>
        [TestVariable("1fce2cd3-b331-40dd-9245-70adfe2e35ca")]
        public string DOM
        {
            get { return _DOM; }
            set { _DOM = value; }
        }

        string _genderCode;

        /// <summary>
        /// Gets or sets the value of variable genderCode.
        /// </summary>
        [TestVariable("cbc6e78f-a969-4e8b-894e-dd70f62ba4ff")]
        public string genderCode
        {
            get { return _genderCode; }
            set { _genderCode = value; }
        }

        string _localityCode;

        /// <summary>
        /// Gets or sets the value of variable localityCode.
        /// </summary>
        [TestVariable("af7b4466-cf19-4bed-bb5a-ba10e2eb16b8")]
        public string localityCode
        {
            get { return _localityCode; }
            set { _localityCode = value; }
        }

        string _postError;

        /// <summary>
        /// Gets or sets the value of variable postError.
        /// </summary>
        [TestVariable("9890c6b6-58d3-4e7b-9fcc-8b647e1af4b3")]
        public string postError
        {
            get { return _postError; }
            set { _postError = value; }
        }

        string _post;

        /// <summary>
        /// Gets or sets the value of variable post.
        /// </summary>
        [TestVariable("e71ec1da-f47d-4dfa-ab50-156efac5f95a")]
        public string post
        {
            get { return _post; }
            set { _post = value; }
        }

        string _visitSessionCode;

        /// <summary>
        /// Gets or sets the value of variable visitSessionCode.
        /// </summary>
        [TestVariable("968c3e2a-3c3b-44b5-a76d-c1cfab210776")]
        public string visitSessionCode
        {
            get { return _visitSessionCode; }
            set { _visitSessionCode = value; }
        }

        string _supervisorid;

        /// <summary>
        /// Gets or sets the value of variable supervisorid.
        /// </summary>
        [TestVariable("c25662f6-4614-4973-83f5-0ab4d98432de")]
        public string supervisorid
        {
            get { return _supervisorid; }
            set { _supervisorid = value; }
        }

        string _TestIdentifier;

        /// <summary>
        /// Gets or sets the value of variable TestIdentifier.
        /// </summary>
        [TestVariable("c36bddc9-c81a-4929-af8a-269c0a92faca")]
        public string TestIdentifier
        {
            get { return _TestIdentifier; }
            set { _TestIdentifier = value; }
        }

        string _externalid;

        /// <summary>
        /// Gets or sets the value of variable externalid.
        /// </summary>
        [TestVariable("b66d511e-e435-4917-8dbb-f16a58c7b6d7")]
        public string externalid
        {
            get { return _externalid; }
            set { _externalid = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            R_runworkflow(authoToken, studyProtocolName, DOM, genderCode, localityCode, postError, post, visitSessionCode, supervisorid, TestIdentifier, externalid);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
