///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PrecisionRecruitment.BatteryTemplatePage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Enter_BatteryTemplate_Description recording.
    /// </summary>
    [TestModule("7c6b57a3-3fc5-43e8-bfa7-47bda1247223", ModuleType.Recording, 1)]
    public partial class Enter_BatteryTemplate_Description : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PrecisionRecruitment.PrecisionRecruitmentRepository repository.
        /// </summary>
        public static PrecisionRecruitment.PrecisionRecruitmentRepository repo = PrecisionRecruitment.PrecisionRecruitmentRepository.Instance;

        static Enter_BatteryTemplate_Description instance = new Enter_BatteryTemplate_Description();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Enter_BatteryTemplate_Description()
        {
            RandNum = "";
            BatteryTemplateDescription = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Enter_BatteryTemplate_Description Instance
        {
            get { return instance; }
        }

#region Variables

        string _BatteryTemplateDescription;

        /// <summary>
        /// Gets or sets the value of variable BatteryTemplateDescription.
        /// </summary>
        [TestVariable("5d9cce39-31e0-463d-855a-63b6718017d4")]
        public string BatteryTemplateDescription
        {
            get { return _BatteryTemplateDescription; }
            set { _BatteryTemplateDescription = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable DOM.
        /// </summary>
        [TestVariable("280aff49-d9c4-468c-bece-6c1951b0ef7e")]
        public string DOM
        {
            get { return repo.DOM; }
            set { repo.DOM = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable RandNum.
        /// </summary>
        [TestVariable("879ea178-bdc2-42e6-b271-105d8a9c7b70")]
        public string RandNum
        {
            get { return repo.RandNum; }
            set { repo.RandNum = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 100;
            Keyboard.DefaultKeyPressTime = 10;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionField' at Center.", repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionFieldInfo, new RecordItemIndex(0));
            repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionField.Click(3);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{End}{LShiftKey down}{Home}{LShiftKey up}{Delete}' with focus on 'CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionField'.", repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionFieldInfo, new RecordItemIndex(1));
            repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionField.PressKeys("{End}{LShiftKey down}{Home}{LShiftKey up}{Delete}", 1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$BatteryTemplateDescription' with focus on 'CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionField'.", repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionFieldInfo, new RecordItemIndex(2));
            repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionField.PressKeys(BatteryTemplateDescription, 1);
            Delay.Milliseconds(10);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$RandNum' with focus on 'CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionField'.", repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionFieldInfo, new RecordItemIndex(3));
            repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionField.PressKeys(RandNum, 1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Value>$BatteryTemplateDescription) on item 'CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionField'.", repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionFieldInfo, new RecordItemIndex(4));
            Validate.AttributeContains(repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionFieldInfo, "Value", BatteryTemplateDescription);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Value>$RandNum) on item 'CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionField'.", repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionFieldInfo, new RecordItemIndex(5));
            Validate.AttributeContains(repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryTemplateDescriptionFieldInfo, "Value", RandNum);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
