///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PrecisionRecruitment.BatteryTemplatePage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validate_BatteryTemplate_Configured recording.
    /// </summary>
    [TestModule("3aa46244-6710-428d-afc1-f5aeed5900e2", ModuleType.Recording, 1)]
    public partial class Validate_BatteryTemplate_Configured : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PrecisionRecruitment.PrecisionRecruitmentRepository repository.
        /// </summary>
        public static PrecisionRecruitment.PrecisionRecruitmentRepository repo = PrecisionRecruitment.PrecisionRecruitmentRepository.Instance;

        static Validate_BatteryTemplate_Configured instance = new Validate_BatteryTemplate_Configured();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validate_BatteryTemplate_Configured()
        {
            BatteryBlockName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validate_BatteryTemplate_Configured Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable DOM.
        /// </summary>
        [TestVariable("280aff49-d9c4-468c-bece-6c1951b0ef7e")]
        public string DOM
        {
            get { return repo.DOM; }
            set { repo.DOM = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable BatteryBlockName.
        /// </summary>
        [TestVariable("4c592594-0ad6-4515-a8bf-ce621aa84724")]
        public string BatteryBlockName
        {
            get { return repo.BatteryBlockName; }
            set { repo.BatteryBlockName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 100;
            Keyboard.DefaultKeyPressTime = 10;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$BatteryBlockName) on item 'CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryBlockCard'.", repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryBlockCardInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.CogstateSolutionPlatform.AddBatteryTemplatePage.BatteryBlockCardInfo, "InnerText", BatteryBlockName);
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "Template Configured Successfully", repo.CogstateSolutionPlatform.Self, false, new RecordItemIndex(1));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
