///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PrecisionRecruitment.BatteryTemplatePage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validate_BatteryTemplate_Entry recording.
    /// </summary>
    [TestModule("08b46a7b-cd12-4842-8e9c-2c245de86a97", ModuleType.Recording, 1)]
    public partial class Validate_BatteryTemplate_Entry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PrecisionRecruitment.PrecisionRecruitmentRepository repository.
        /// </summary>
        public static PrecisionRecruitment.PrecisionRecruitmentRepository repo = PrecisionRecruitment.PrecisionRecruitmentRepository.Instance;

        static Validate_BatteryTemplate_Entry instance = new Validate_BatteryTemplate_Entry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validate_BatteryTemplate_Entry()
        {
            RandNum = "";
            BatteryTemplateName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validate_BatteryTemplate_Entry Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable DOM.
        /// </summary>
        [TestVariable("280aff49-d9c4-468c-bece-6c1951b0ef7e")]
        public string DOM
        {
            get { return repo.DOM; }
            set { repo.DOM = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable BatteryTemplateName.
        /// </summary>
        [TestVariable("d424b612-6d80-443b-9a05-dc5e51c6afb2")]
        public string BatteryTemplateName
        {
            get { return repo.BatteryTemplateName; }
            set { repo.BatteryTemplateName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable RandNum.
        /// </summary>
        [TestVariable("8ec1c4ad-38f3-4ed8-af2f-934f245aaa32")]
        public string RandNum
        {
            get { return repo.RandNum; }
            set { repo.RandNum = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 100;
            Keyboard.DefaultKeyPressTime = 10;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$BatteryTemplateName) on item 'CogstateSolutionPlatform.Breadcrumbs.BatteryTemplateNameBreadcrumb'.", repo.CogstateSolutionPlatform.Breadcrumbs.BatteryTemplateNameBreadcrumbInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.CogstateSolutionPlatform.Breadcrumbs.BatteryTemplateNameBreadcrumbInfo, "InnerText", BatteryTemplateName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$RandNum) on item 'CogstateSolutionPlatform.Breadcrumbs.BatteryTemplateNameBreadcrumb'.", repo.CogstateSolutionPlatform.Breadcrumbs.BatteryTemplateNameBreadcrumbInfo, new RecordItemIndex(1));
            Validate.AttributeContains(repo.CogstateSolutionPlatform.Breadcrumbs.BatteryTemplateNameBreadcrumbInfo, "InnerText", RandNum);
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "Battery Template Added Successfully", repo.CogstateSolutionPlatform.Self, false, new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
