///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DCT
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DCTRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("1559d85e-a9d4-499b-8b78-a53d7c7c1eef")]
    public partial class DCTRepository : RepoGenBaseFolder
    {
        static DCTRepository instance = new DCTRepository();
        DCTRepositoryFolders.DataCleaningToolAppFolder _datacleaningtool;
        DCTRepositoryFolders.DataCleaningToolGoogleChromeAppFolder _datacleaningtoolgooglechrome;
        DCTRepositoryFolders.OctopusDeployAppFolder _octopusdeploy;
        DCTRepositoryFolders.OverviewOctopusDeployGoogleChromAppFolder _overviewoctopusdeploygooglechrom;
        DCTRepositoryFolders.REDCapCloudAppFolder _redcapcloud;
        DCTRepositoryFolders.LeaveSiteAppFolder _leavesite;
        DCTRepositoryFolders.SignInAppFolder _signin;
        DCTRepositoryFolders.SignInToYourAccountAppFolder _signintoyouraccount;
        DCTRepositoryFolders.REDCapCloudGoogleChromeAppFolder _redcapcloudgooglechrome;
        DCTRepositoryFolders.KuduServicesAppFolder _kuduservices;
        DCTRepositoryFolders.CogstateSolutionPlatformAppFolder _cogstatesolutionplatform;
        DCTRepositoryFolders.AcademicExtractOrrPowerBIAppFolder _academicextractorrpowerbi;
        DCTRepositoryFolders.REDCapCloud1AppFolder _redcapcloud1;
        DCTRepositoryFolders.DataCleaningTool1AppFolder _datacleaningtool1;

        /// <summary>
        /// Gets the singleton class instance representing the DCTRepository element repository.
        /// </summary>
        [RepositoryFolder("1559d85e-a9d4-499b-8b78-a53d7c7c1eef")]
        public static DCTRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DCTRepository() 
            : base("DCTRepository", "/", null, 0, false, "1559d85e-a9d4-499b-8b78-a53d7c7c1eef", ".\\RepositoryImages\\DCTRepository1559d85e.rximgres")
        {
            _datacleaningtool = new DCTRepositoryFolders.DataCleaningToolAppFolder(this);
            _datacleaningtoolgooglechrome = new DCTRepositoryFolders.DataCleaningToolGoogleChromeAppFolder(this);
            _octopusdeploy = new DCTRepositoryFolders.OctopusDeployAppFolder(this);
            _overviewoctopusdeploygooglechrom = new DCTRepositoryFolders.OverviewOctopusDeployGoogleChromAppFolder(this);
            _redcapcloud = new DCTRepositoryFolders.REDCapCloudAppFolder(this);
            _leavesite = new DCTRepositoryFolders.LeaveSiteAppFolder(this);
            _signin = new DCTRepositoryFolders.SignInAppFolder(this);
            _signintoyouraccount = new DCTRepositoryFolders.SignInToYourAccountAppFolder(this);
            _redcapcloudgooglechrome = new DCTRepositoryFolders.REDCapCloudGoogleChromeAppFolder(this);
            _kuduservices = new DCTRepositoryFolders.KuduServicesAppFolder(this);
            _cogstatesolutionplatform = new DCTRepositoryFolders.CogstateSolutionPlatformAppFolder(this);
            _academicextractorrpowerbi = new DCTRepositoryFolders.AcademicExtractOrrPowerBIAppFolder(this);
            _redcapcloud1 = new DCTRepositoryFolders.REDCapCloud1AppFolder(this);
            _datacleaningtool1 = new DCTRepositoryFolders.DataCleaningTool1AppFolder(this);
        }

#region Variables

        string _ExistingStudy = "";

        /// <summary>
        /// Gets or sets the value of variable ExistingStudy.
        /// </summary>
        [TestVariable("ee00695b-ccc6-4286-ad8b-942dd6f880b2")]
        public string ExistingStudy
        {
            get { return _ExistingStudy; }
            set { _ExistingStudy = value; }
        }

        string _RandNum = "";

        /// <summary>
        /// Gets or sets the value of variable RandNum.
        /// </summary>
        [TestVariable("0a1f4511-792f-4cbf-818c-dcbe6257b7c8")]
        public string RandNum
        {
            get { return _RandNum; }
            set { _RandNum = value; }
        }

        string _CSPDOM = "";

        /// <summary>
        /// Gets or sets the value of variable CSPDOM.
        /// </summary>
        [TestVariable("4868fd53-f0cc-4bcc-ad64-84d67b341b4d")]
        public string CSPDOM
        {
            get { return _CSPDOM; }
            set { _CSPDOM = value; }
        }

        string _AzureDOM = "cgst-qc-orr-hub.scm.azurewebsites.net";

        /// <summary>
        /// Gets or sets the value of variable AzureDOM.
        /// </summary>
        [TestVariable("49e5b85f-1ec2-4934-a251-0656cf1bbe62")]
        public string AzureDOM
        {
            get { return _AzureDOM; }
            set { _AzureDOM = value; }
        }

        string _CSPUsername = "";

        /// <summary>
        /// Gets or sets the value of variable CSPUsername.
        /// </summary>
        [TestVariable("d56d6003-1d1a-4dc0-866d-e61b87da582b")]
        public string CSPUsername
        {
            get { return _CSPUsername; }
            set { _CSPUsername = value; }
        }

        string _DCTDOM = "";

        /// <summary>
        /// Gets or sets the value of variable DCTDOM.
        /// </summary>
        [TestVariable("b4062045-8a57-448e-b3d6-6bd8f25d8dad")]
        public string DCTDOM
        {
            get { return _DCTDOM; }
            set { _DCTDOM = value; }
        }

        string _RCCDOM = "cgsqc.redcapcloud.com";

        /// <summary>
        /// Gets or sets the value of variable RCCDOM.
        /// </summary>
        [TestVariable("5a760c9f-9fed-4f01-8c4c-f1cd491cbeda")]
        public string RCCDOM
        {
            get { return _RCCDOM; }
            set { _RCCDOM = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1559d85e-a9d4-499b-8b78-a53d7c7c1eef")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DataCleaningTool folder.
        /// </summary>
        [RepositoryFolder("8d2bb7de-1088-4124-a99c-b77e11c31af1")]
        public virtual DCTRepositoryFolders.DataCleaningToolAppFolder DataCleaningTool
        {
            get { return _datacleaningtool; }
        }

        /// <summary>
        /// The DataCleaningToolGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("c8b15f67-a005-4c0a-b1ad-7978cae56a3f")]
        public virtual DCTRepositoryFolders.DataCleaningToolGoogleChromeAppFolder DataCleaningToolGoogleChrome
        {
            get { return _datacleaningtoolgooglechrome; }
        }

        /// <summary>
        /// The OctopusDeploy folder.
        /// </summary>
        [RepositoryFolder("3a3def39-3ad2-4434-8253-957aa95ab688")]
        public virtual DCTRepositoryFolders.OctopusDeployAppFolder OctopusDeploy
        {
            get { return _octopusdeploy; }
        }

        /// <summary>
        /// The OverviewOctopusDeployGoogleChrom folder.
        /// </summary>
        [RepositoryFolder("ccf2a4a6-903a-4702-a5ac-46b9a10f9ea1")]
        public virtual DCTRepositoryFolders.OverviewOctopusDeployGoogleChromAppFolder OverviewOctopusDeployGoogleChrom
        {
            get { return _overviewoctopusdeploygooglechrom; }
        }

        /// <summary>
        /// The REDCapCloud folder.
        /// </summary>
        [RepositoryFolder("8c57a700-52e3-43b0-bb42-688fd9e5c8b2")]
        public virtual DCTRepositoryFolders.REDCapCloudAppFolder REDCapCloud
        {
            get { return _redcapcloud; }
        }

        /// <summary>
        /// The LeaveSite folder.
        /// </summary>
        [RepositoryFolder("67e4e3c1-b80e-4916-ac48-42c2ed4dae8b")]
        public virtual DCTRepositoryFolders.LeaveSiteAppFolder LeaveSite
        {
            get { return _leavesite; }
        }

        /// <summary>
        /// The SignIn folder.
        /// </summary>
        [RepositoryFolder("29fb0691-ee86-4289-abe1-a78470d5da1d")]
        public virtual DCTRepositoryFolders.SignInAppFolder SignIn
        {
            get { return _signin; }
        }

        /// <summary>
        /// The SignInToYourAccount folder.
        /// </summary>
        [RepositoryFolder("e1e54a0b-d167-4616-8313-fb55e887a8fc")]
        public virtual DCTRepositoryFolders.SignInToYourAccountAppFolder SignInToYourAccount
        {
            get { return _signintoyouraccount; }
        }

        /// <summary>
        /// The REDCapCloudGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("c3587369-faf2-4be6-a9b8-82cc31d5ad93")]
        public virtual DCTRepositoryFolders.REDCapCloudGoogleChromeAppFolder REDCapCloudGoogleChrome
        {
            get { return _redcapcloudgooglechrome; }
        }

        /// <summary>
        /// The KuduServices folder.
        /// </summary>
        [RepositoryFolder("83d87542-91e4-4062-831c-e71dae0b7938")]
        public virtual DCTRepositoryFolders.KuduServicesAppFolder KuduServices
        {
            get { return _kuduservices; }
        }

        /// <summary>
        /// The CogstateSolutionPlatform folder.
        /// </summary>
        [RepositoryFolder("38465dbb-2a52-4f97-a7da-4f756315b3f4")]
        public virtual DCTRepositoryFolders.CogstateSolutionPlatformAppFolder CogstateSolutionPlatform
        {
            get { return _cogstatesolutionplatform; }
        }

        /// <summary>
        /// The AcademicExtractOrrPowerBI folder.
        /// </summary>
        [RepositoryFolder("f1e3226f-4e04-44a6-8973-7f7dc740f469")]
        public virtual DCTRepositoryFolders.AcademicExtractOrrPowerBIAppFolder AcademicExtractOrrPowerBI
        {
            get { return _academicextractorrpowerbi; }
        }

        /// <summary>
        /// The REDCapCloud1 folder.
        /// </summary>
        [RepositoryFolder("ee5f1b78-cba3-4623-b016-bbed2259c88e")]
        public virtual DCTRepositoryFolders.REDCapCloud1AppFolder REDCapCloud1
        {
            get { return _redcapcloud1; }
        }

        /// <summary>
        /// The DataCleaningTool1 folder.
        /// </summary>
        [RepositoryFolder("c999cc24-7711-432b-bcf1-273bdadd7e3f")]
        public virtual DCTRepositoryFolders.DataCleaningTool1AppFolder DataCleaningTool1
        {
            get { return _datacleaningtool1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class DCTRepositoryFolders
    {
        /// <summary>
        /// The DataCleaningToolAppFolder folder.
        /// </summary>
        [RepositoryFolder("8d2bb7de-1088-4124-a99c-b77e11c31af1")]
        public partial class DataCleaningToolAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _movevalidationInfo;
            RepoItemInfo _primaryvalidationInfo;
            RepoItemInfo _invalidbuttonInfo;
            RepoItemInfo _restorebutton_Info;
            RepoItemInfo _findbyassessmentidbuttonInfo;
            RepoItemInfo _openresultsInfo;
            RepoItemInfo _clickconfirmInfo;
            RepoItemInfo _clickmakeprimaryInfo;
            RepoItemInfo _clickmovebuttonInfo;
            RepoItemInfo _entertestidentifierInfo;
            RepoItemInfo _clickokInfo;
            RepoItemInfo _clearprimaryInfo;
            RepoItemInfo _confirminvalidateInfo;
            RepoItemInfo _destinationvisitfieldInfo;
            RepoItemInfo _destinationsubjectfieldInfo;
            RepoItemInfo _nooptionsitemInfo;

            /// <summary>
            /// Creates a new DataCleaningTool  folder.
            /// </summary>
            public DataCleaningToolAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DataCleaningTool", "/dom[@domain=$DCTDOM]", parentFolder, 30000, null, false, "8d2bb7de-1088-4124-a99c-b77e11c31af1", "")
            {
                _movevalidationInfo = new RepoItemInfo(this, "MoveValidation", ".//div[#'root']/div/div/div[3]/p[@innertext='No results found.']", 30000, null, "178b44c8-a649-4b52-b5b7-b56b4cde9123");
                _primaryvalidationInfo = new RepoItemInfo(this, "PrimaryValidation", ".//div[#'root']/div/div/div[3]/?/?/table//td[@innertext='yes']", 30000, null, "1a031ccd-10c6-432c-9edf-5a8661be8d93");
                _invalidbuttonInfo = new RepoItemInfo(this, "InvalidButton", ".//button[#'action-row-invalidate-button']", 30000, null, "d51ef50b-cc93-42e6-9669-6ad2db192605");
                _restorebutton_Info = new RepoItemInfo(this, "RestoreButton_", ".//button[#'action-row-restore-button']/span[@innertext='restore']", 30000, null, "dcad520b-c5c1-43c8-84e3-9c49e20656ca");
                _findbyassessmentidbuttonInfo = new RepoItemInfo(this, "FindByAssessmentIdButton", ".//div[#'root']/div/div/div[2]/div[2]/?/?/span[@innertext='Find By Assessment Id']", 30000, null, "98cfba2b-c4c5-488d-8805-d8e0193ff5bb");
                _openresultsInfo = new RepoItemInfo(this, "OpenResults", ".//div[#'root']/div/div/div[3]/?/?/table//td[@innertext~'2019-']", 30000, null, "2f9f79e7-580e-4755-a6bc-f7137da21cde");
                _clickconfirmInfo = new RepoItemInfo(this, "ClickConfirm", ".//button[#'move-confirmation-button-next']", 30000, null, "67c5cfc6-aa95-441f-bd70-e6ac84c9e2f1");
                _clickmakeprimaryInfo = new RepoItemInfo(this, "ClickMakePrimary", ".//button[#'action-row-make-primary-button']/span[@innertext='make primary']", 30000, null, "8a0da0d6-6903-467a-8b3a-441a0225f30c");
                _clickmovebuttonInfo = new RepoItemInfo(this, "ClickMoveButton", ".//button[#'action-row-move-button']/span[@innertext='move']", 30000, null, "4475259d-22a2-4512-a4b1-742099f24bb9");
                _entertestidentifierInfo = new RepoItemInfo(this, "EnterTestIdentifier", ".//input[#'findByAssessmentId']", 30000, null, "86244d71-2a9e-4044-a2a8-18c3c1d6851b");
                _clickokInfo = new RepoItemInfo(this, "ClickOk", ".//button[#'move-selection-button-next']/span[@innertext='ok']", 30000, null, "4ac58619-4351-44b7-8087-c4e6656d9855");
                _clearprimaryInfo = new RepoItemInfo(this, "ClearPrimary", ".//button[#'action-row-clear-primary-button']/span[@innertext='clear primary']", 30000, null, "e0ce542a-7e79-45b6-ba96-42c007565214");
                _confirminvalidateInfo = new RepoItemInfo(this, "ConfirmInvalidate", ".//span[@innertext='confirm']", 30000, null, "6d6c847e-4c07-4fd7-b4fe-d45d0f9fbaf2");
                _destinationvisitfieldInfo = new RepoItemInfo(this, "DestinationVisitField", ".//label[@innertext='Visit']", 30000, null, "5f30ccb2-6e51-4bf4-ad65-fe31a1cdef34");
                _destinationsubjectfieldInfo = new RepoItemInfo(this, "DestinationSubjectField", ".//label[@innertext='Subject']", 30000, null, "6bccceed-5896-4d21-9e92-2b50db29405f");
                _nooptionsitemInfo = new RepoItemInfo(this, "NoOptionsItem", ".//body//div//p[@innertext='No Options']", 30000, null, "596463e8-50fb-4832-8fe5-c3358e0a090d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8d2bb7de-1088-4124-a99c-b77e11c31af1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8d2bb7de-1088-4124-a99c-b77e11c31af1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MoveValidation item.
            /// </summary>
            [RepositoryItem("178b44c8-a649-4b52-b5b7-b56b4cde9123")]
            public virtual Ranorex.PTag MoveValidation
            {
                get
                {
                    return _movevalidationInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The MoveValidation item info.
            /// </summary>
            [RepositoryItemInfo("178b44c8-a649-4b52-b5b7-b56b4cde9123")]
            public virtual RepoItemInfo MoveValidationInfo
            {
                get
                {
                    return _movevalidationInfo;
                }
            }

            /// <summary>
            /// The PrimaryValidation item.
            /// </summary>
            [RepositoryItem("1a031ccd-10c6-432c-9edf-5a8661be8d93")]
            public virtual Ranorex.TdTag PrimaryValidation
            {
                get
                {
                    return _primaryvalidationInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The PrimaryValidation item info.
            /// </summary>
            [RepositoryItemInfo("1a031ccd-10c6-432c-9edf-5a8661be8d93")]
            public virtual RepoItemInfo PrimaryValidationInfo
            {
                get
                {
                    return _primaryvalidationInfo;
                }
            }

            /// <summary>
            /// The InvalidButton item.
            /// </summary>
            [RepositoryItem("d51ef50b-cc93-42e6-9669-6ad2db192605")]
            public virtual Ranorex.ButtonTag InvalidButton
            {
                get
                {
                    return _invalidbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The InvalidButton item info.
            /// </summary>
            [RepositoryItemInfo("d51ef50b-cc93-42e6-9669-6ad2db192605")]
            public virtual RepoItemInfo InvalidButtonInfo
            {
                get
                {
                    return _invalidbuttonInfo;
                }
            }

            /// <summary>
            /// The RestoreButton_ item.
            /// </summary>
            [RepositoryItem("dcad520b-c5c1-43c8-84e3-9c49e20656ca")]
            public virtual Ranorex.SpanTag RestoreButton_
            {
                get
                {
                    return _restorebutton_Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RestoreButton_ item info.
            /// </summary>
            [RepositoryItemInfo("dcad520b-c5c1-43c8-84e3-9c49e20656ca")]
            public virtual RepoItemInfo RestoreButton_Info
            {
                get
                {
                    return _restorebutton_Info;
                }
            }

            /// <summary>
            /// The FindByAssessmentIdButton item.
            /// </summary>
            [RepositoryItem("98cfba2b-c4c5-488d-8805-d8e0193ff5bb")]
            public virtual Ranorex.SpanTag FindByAssessmentIdButton
            {
                get
                {
                    return _findbyassessmentidbuttonInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The FindByAssessmentIdButton item info.
            /// </summary>
            [RepositoryItemInfo("98cfba2b-c4c5-488d-8805-d8e0193ff5bb")]
            public virtual RepoItemInfo FindByAssessmentIdButtonInfo
            {
                get
                {
                    return _findbyassessmentidbuttonInfo;
                }
            }

            /// <summary>
            /// The OpenResults item.
            /// </summary>
            [RepositoryItem("2f9f79e7-580e-4755-a6bc-f7137da21cde")]
            public virtual Ranorex.TdTag OpenResults
            {
                get
                {
                    return _openresultsInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The OpenResults item info.
            /// </summary>
            [RepositoryItemInfo("2f9f79e7-580e-4755-a6bc-f7137da21cde")]
            public virtual RepoItemInfo OpenResultsInfo
            {
                get
                {
                    return _openresultsInfo;
                }
            }

            /// <summary>
            /// The ClickConfirm item.
            /// </summary>
            [RepositoryItem("67c5cfc6-aa95-441f-bd70-e6ac84c9e2f1")]
            public virtual Ranorex.Button ClickConfirm
            {
                get
                {
                    return _clickconfirmInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ClickConfirm item info.
            /// </summary>
            [RepositoryItemInfo("67c5cfc6-aa95-441f-bd70-e6ac84c9e2f1")]
            public virtual RepoItemInfo ClickConfirmInfo
            {
                get
                {
                    return _clickconfirmInfo;
                }
            }

            /// <summary>
            /// The ClickMakePrimary item.
            /// </summary>
            [RepositoryItem("8a0da0d6-6903-467a-8b3a-441a0225f30c")]
            public virtual Ranorex.SpanTag ClickMakePrimary
            {
                get
                {
                    return _clickmakeprimaryInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ClickMakePrimary item info.
            /// </summary>
            [RepositoryItemInfo("8a0da0d6-6903-467a-8b3a-441a0225f30c")]
            public virtual RepoItemInfo ClickMakePrimaryInfo
            {
                get
                {
                    return _clickmakeprimaryInfo;
                }
            }

            /// <summary>
            /// The ClickMoveButton item.
            /// </summary>
            [RepositoryItem("4475259d-22a2-4512-a4b1-742099f24bb9")]
            public virtual Ranorex.SpanTag ClickMoveButton
            {
                get
                {
                    return _clickmovebuttonInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ClickMoveButton item info.
            /// </summary>
            [RepositoryItemInfo("4475259d-22a2-4512-a4b1-742099f24bb9")]
            public virtual RepoItemInfo ClickMoveButtonInfo
            {
                get
                {
                    return _clickmovebuttonInfo;
                }
            }

            /// <summary>
            /// The EnterTestIdentifier item.
            /// </summary>
            [RepositoryItem("86244d71-2a9e-4044-a2a8-18c3c1d6851b")]
            public virtual Ranorex.InputTag EnterTestIdentifier
            {
                get
                {
                    return _entertestidentifierInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EnterTestIdentifier item info.
            /// </summary>
            [RepositoryItemInfo("86244d71-2a9e-4044-a2a8-18c3c1d6851b")]
            public virtual RepoItemInfo EnterTestIdentifierInfo
            {
                get
                {
                    return _entertestidentifierInfo;
                }
            }

            /// <summary>
            /// The ClickOk item.
            /// </summary>
            [RepositoryItem("4ac58619-4351-44b7-8087-c4e6656d9855")]
            public virtual Ranorex.SpanTag ClickOk
            {
                get
                {
                    return _clickokInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ClickOk item info.
            /// </summary>
            [RepositoryItemInfo("4ac58619-4351-44b7-8087-c4e6656d9855")]
            public virtual RepoItemInfo ClickOkInfo
            {
                get
                {
                    return _clickokInfo;
                }
            }

            /// <summary>
            /// The ClearPrimary item.
            /// </summary>
            [RepositoryItem("e0ce542a-7e79-45b6-ba96-42c007565214")]
            public virtual Ranorex.SpanTag ClearPrimary
            {
                get
                {
                    return _clearprimaryInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ClearPrimary item info.
            /// </summary>
            [RepositoryItemInfo("e0ce542a-7e79-45b6-ba96-42c007565214")]
            public virtual RepoItemInfo ClearPrimaryInfo
            {
                get
                {
                    return _clearprimaryInfo;
                }
            }

            /// <summary>
            /// The ConfirmInvalidate item.
            /// </summary>
            [RepositoryItem("6d6c847e-4c07-4fd7-b4fe-d45d0f9fbaf2")]
            public virtual Ranorex.SpanTag ConfirmInvalidate
            {
                get
                {
                    return _confirminvalidateInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ConfirmInvalidate item info.
            /// </summary>
            [RepositoryItemInfo("6d6c847e-4c07-4fd7-b4fe-d45d0f9fbaf2")]
            public virtual RepoItemInfo ConfirmInvalidateInfo
            {
                get
                {
                    return _confirminvalidateInfo;
                }
            }

            /// <summary>
            /// The DestinationVisitField item.
            /// </summary>
            [RepositoryItem("5f30ccb2-6e51-4bf4-ad65-fe31a1cdef34")]
            public virtual Ranorex.LabelTag DestinationVisitField
            {
                get
                {
                    return _destinationvisitfieldInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The DestinationVisitField item info.
            /// </summary>
            [RepositoryItemInfo("5f30ccb2-6e51-4bf4-ad65-fe31a1cdef34")]
            public virtual RepoItemInfo DestinationVisitFieldInfo
            {
                get
                {
                    return _destinationvisitfieldInfo;
                }
            }

            /// <summary>
            /// The DestinationSubjectField item.
            /// </summary>
            [RepositoryItem("6bccceed-5896-4d21-9e92-2b50db29405f")]
            public virtual Ranorex.LabelTag DestinationSubjectField
            {
                get
                {
                    return _destinationsubjectfieldInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The DestinationSubjectField item info.
            /// </summary>
            [RepositoryItemInfo("6bccceed-5896-4d21-9e92-2b50db29405f")]
            public virtual RepoItemInfo DestinationSubjectFieldInfo
            {
                get
                {
                    return _destinationsubjectfieldInfo;
                }
            }

            /// <summary>
            /// The NoOptionsItem item.
            /// </summary>
            [RepositoryItem("596463e8-50fb-4832-8fe5-c3358e0a090d")]
            public virtual Ranorex.PTag NoOptionsItem
            {
                get
                {
                    return _nooptionsitemInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The NoOptionsItem item info.
            /// </summary>
            [RepositoryItemInfo("596463e8-50fb-4832-8fe5-c3358e0a090d")]
            public virtual RepoItemInfo NoOptionsItemInfo
            {
                get
                {
                    return _nooptionsitemInfo;
                }
            }
        }

        /// <summary>
        /// The DataCleaningToolGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("c8b15f67-a005-4c0a-b1ad-7978cae56a3f")]
        public partial class DataCleaningToolGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closappInfo;

            /// <summary>
            /// Creates a new DataCleaningToolGoogleChrome  folder.
            /// </summary>
            public DataCleaningToolGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DataCleaningToolGoogleChrome", "/form[@title~'^Data\\ Cleaning\\ Tool\\ -\\ Goog']", parentFolder, 30000, null, true, "c8b15f67-a005-4c0a-b1ad-7978cae56a3f", "")
            {
                _closappInfo = new RepoItemInfo(this, "ClosApp", ".//element[@accessiblename='Infobar']", 30000, null, "063547b3-c1fe-47cf-84c0-38d75dad0d37");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c8b15f67-a005-4c0a-b1ad-7978cae56a3f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c8b15f67-a005-4c0a-b1ad-7978cae56a3f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ClosApp item.
            /// </summary>
            [RepositoryItem("063547b3-c1fe-47cf-84c0-38d75dad0d37")]
            public virtual Ranorex.Unknown ClosApp
            {
                get
                {
                    return _closappInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ClosApp item info.
            /// </summary>
            [RepositoryItemInfo("063547b3-c1fe-47cf-84c0-38d75dad0d37")]
            public virtual RepoItemInfo ClosAppInfo
            {
                get
                {
                    return _closappInfo;
                }
            }
        }

        /// <summary>
        /// The OctopusDeployAppFolder folder.
        /// </summary>
        [RepositoryFolder("3a3def39-3ad2-4434-8253-957aa95ab688")]
        public partial class OctopusDeployAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clickloginInfo;
            RepoItemInfo _spantagdctInfo;
            RepoItemInfo _dct_versionvalidationInfo;
            RepoItemInfo _octopuslogoutInfo;
            RepoItemInfo _signoutInfo;

            /// <summary>
            /// Creates a new OctopusDeploy  folder.
            /// </summary>
            public OctopusDeployAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OctopusDeploy", "/dom[@domain='octopus.cogstate.com']", parentFolder, 30000, null, false, "3a3def39-3ad2-4434-8253-957aa95ab688", "")
            {
                _clickloginInfo = new RepoItemInfo(this, "ClickLogin", ".//div[@innertext='Sign in with Microsoft']", 30000, null, "b64ce1a7-413e-4c7d-982c-e30258f01ef7");
                _spantagdctInfo = new RepoItemInfo(this, "SpanTagDCT", ".//tag[@innertext='DCT']", 30000, null, "a9d7fbd8-9953-4653-b88a-a2c645191e5b");
                _dct_versionvalidationInfo = new RepoItemInfo(this, "DCT_VersionValidation", ".//span[@innertext~'1.1.']", 30000, null, "0a703cdb-20d6-4cf2-a43f-c75d08312d13");
                _octopuslogoutInfo = new RepoItemInfo(this, "OctopusLogout", ".//div[#'topnavbar']/div/nav[2]//em", 30000, null, "345f9af0-bbb9-471f-a317-13ac2f21aa46");
                _signoutInfo = new RepoItemInfo(this, "SIGNOUT", ".//div[#'app']/div/div/div[2]/div[1]/?/?/button[@title='SIGN OUT']//span[@innertext='SIGN OUT']", 30000, null, "97cee7fb-bf55-4da1-9a16-95516885255c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3a3def39-3ad2-4434-8253-957aa95ab688")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3a3def39-3ad2-4434-8253-957aa95ab688")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ClickLogin item.
            /// </summary>
            [RepositoryItem("b64ce1a7-413e-4c7d-982c-e30258f01ef7")]
            public virtual Ranorex.DivTag ClickLogin
            {
                get
                {
                    return _clickloginInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ClickLogin item info.
            /// </summary>
            [RepositoryItemInfo("b64ce1a7-413e-4c7d-982c-e30258f01ef7")]
            public virtual RepoItemInfo ClickLoginInfo
            {
                get
                {
                    return _clickloginInfo;
                }
            }

            /// <summary>
            /// The SpanTagDCT item.
            /// </summary>
            [RepositoryItem("a9d7fbd8-9953-4653-b88a-a2c645191e5b")]
            public virtual Ranorex.WebElement SpanTagDCT
            {
                get
                {
                    return _spantagdctInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The SpanTagDCT item info.
            /// </summary>
            [RepositoryItemInfo("a9d7fbd8-9953-4653-b88a-a2c645191e5b")]
            public virtual RepoItemInfo SpanTagDCTInfo
            {
                get
                {
                    return _spantagdctInfo;
                }
            }

            /// <summary>
            /// The DCT_VersionValidation item.
            /// </summary>
            [RepositoryItem("0a703cdb-20d6-4cf2-a43f-c75d08312d13")]
            public virtual Ranorex.SpanTag DCT_VersionValidation
            {
                get
                {
                    return _dct_versionvalidationInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The DCT_VersionValidation item info.
            /// </summary>
            [RepositoryItemInfo("0a703cdb-20d6-4cf2-a43f-c75d08312d13")]
            public virtual RepoItemInfo DCT_VersionValidationInfo
            {
                get
                {
                    return _dct_versionvalidationInfo;
                }
            }

            /// <summary>
            /// The OctopusLogout item.
            /// </summary>
            [RepositoryItem("345f9af0-bbb9-471f-a317-13ac2f21aa46")]
            public virtual Ranorex.EmTag OctopusLogout
            {
                get
                {
                    return _octopuslogoutInfo.CreateAdapter<Ranorex.EmTag>(true);
                }
            }

            /// <summary>
            /// The OctopusLogout item info.
            /// </summary>
            [RepositoryItemInfo("345f9af0-bbb9-471f-a317-13ac2f21aa46")]
            public virtual RepoItemInfo OctopusLogoutInfo
            {
                get
                {
                    return _octopuslogoutInfo;
                }
            }

            /// <summary>
            /// The SIGNOUT item.
            /// </summary>
            [RepositoryItem("97cee7fb-bf55-4da1-9a16-95516885255c")]
            public virtual Ranorex.SpanTag SIGNOUT
            {
                get
                {
                    return _signoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SIGNOUT item info.
            /// </summary>
            [RepositoryItemInfo("97cee7fb-bf55-4da1-9a16-95516885255c")]
            public virtual RepoItemInfo SIGNOUTInfo
            {
                get
                {
                    return _signoutInfo;
                }
            }
        }

        /// <summary>
        /// The OverviewOctopusDeployGoogleChromAppFolder folder.
        /// </summary>
        [RepositoryFolder("ccf2a4a6-903a-4702-a5ac-46b9a10f9ea1")]
        public partial class OverviewOctopusDeployGoogleChromAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closepageInfo;

            /// <summary>
            /// Creates a new OverviewOctopusDeployGoogleChrom  folder.
            /// </summary>
            public OverviewOctopusDeployGoogleChromAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OverviewOctopusDeployGoogleChrom", "/form[@title~'^Overview\\ -\\ Octopus\\ Deploy']", parentFolder, 30000, null, true, "ccf2a4a6-903a-4702-a5ac-46b9a10f9ea1", "")
            {
                _closepageInfo = new RepoItemInfo(this, "ClosePage", "container[@accessiblename~'^Overview\\ -\\ Octopus\\ Deploy']/container/container[2]/container[1]", 30000, null, "3354b5b3-888d-4a90-aca5-79270cb09f08");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ccf2a4a6-903a-4702-a5ac-46b9a10f9ea1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ccf2a4a6-903a-4702-a5ac-46b9a10f9ea1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ClosePage item.
            /// </summary>
            [RepositoryItem("3354b5b3-888d-4a90-aca5-79270cb09f08")]
            public virtual Ranorex.Container ClosePage
            {
                get
                {
                    return _closepageInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ClosePage item info.
            /// </summary>
            [RepositoryItemInfo("3354b5b3-888d-4a90-aca5-79270cb09f08")]
            public virtual RepoItemInfo ClosePageInfo
            {
                get
                {
                    return _closepageInfo;
                }
            }
        }

        /// <summary>
        /// The REDCapCloudAppFolder folder.
        /// </summary>
        [RepositoryFolder("8c57a700-52e3-43b0-bb42-688fd9e5c8b2")]
        public partial class REDCapCloudAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _searchstudyinrccInfo;
            RepoItemInfo _existingrccstudyInfo;
            RepoItemInfo _clicksubjectInfo;
            RepoItemInfo _opensubjectInfo;
            RepoItemInfo _openevent_Info;
            RepoItemInfo _clickstarttestInfo;
            RepoItemInfo _beginassessmentInfo;
            RepoItemInfo _clcikyesInfo;
            RepoItemInfo _compositeoutcomeInfo;
            RepoItemInfo _loginusernameInfo;
            RepoItemInfo _loginapplybuttonInfo;
            RepoItemInfo _loginpasswordInfo;
            DataCollectionWidgetCheckboxCompleteInfoClass _datacollectionwidgetcheckboxcompleteInfo;
            RepoItemInfo _addsubjectInfo;
            RepoItemInfo _sitesbuttonInfo;
            RepoItemInfo _selectsiteInfo;
            RepoItemInfo _subjectnumberInfo;
            RepoItemInfo _saveandenterdatabuttonInfo;

            /// <summary>
            /// Creates a new REDCapCloud  folder.
            /// </summary>
            public REDCapCloudAppFolder(RepoGenBaseFolder parentFolder) :
                    base("REDCapCloud", "/dom[@domain=$RCCDOM]", parentFolder, 30000, null, false, "8c57a700-52e3-43b0-bb42-688fd9e5c8b2", "")
            {
                _searchstudyinrccInfo = new RepoItemInfo(this, "SearchStudyInRCC", ".//input[#'filtersWidget_userInputWidget_studyName']", 30000, null, "1aaeabd0-d27c-4203-9346-f994a87bad37");
                _existingrccstudyInfo = new RepoItemInfo(this, "ExistingRCCStudy", ".//div[@innertext=$ExistingStudy]", 30000, null, "e497ee0e-507a-42d4-8dbc-21b179383f59");
                _clicksubjectInfo = new RepoItemInfo(this, "ClickSubject", ".//div[#'leftMenuButtons_navSubjects']", 30000, null, "e5549fed-7e0e-4f0c-a146-6e802d0e81db");
                _opensubjectInfo = new RepoItemInfo(this, "OpenSubject", ".//div[@innertext~'2019']", 30000, null, "eae74a37-456a-4128-b4d8-a07f476da351");
                _openevent_Info = new RepoItemInfo(this, "OpenEvent_", ".//div[@innertext='Visit1']", 30000, null, "e1819309-f7a5-4368-aa69-80d60e74fc27");
                _clickstarttestInfo = new RepoItemInfo(this, "ClickStartTest", ".//div[#'subjectMatrixByEventsViewAbstract_rowCrfName_beginCogstateBattery']", 30000, null, "fb671e3e-2a1e-498e-897a-9088a17ab693");
                _beginassessmentInfo = new RepoItemInfo(this, "BeginAssessment", ".//span[@innertext='Begin Assessment']", 30000, null, "0e9fb7e7-6075-4e54-adef-cd32527d42cc");
                _clcikyesInfo = new RepoItemInfo(this, "ClcikYes", ".//button[#'commonTools_buttonYes']/span[@innertext='Yes']", 30000, null, "fa7f40ce-5cb8-4540-9101-1575b6fd6412");
                _compositeoutcomeInfo = new RepoItemInfo(this, "CompositeOutcome", ".//div[#'subjectMatrixByEventsViewAbstract_rowCrfName_cogstateBatteryCRF-CompositeOutcomes']", 30000, null, "c30cba75-1d90-4d95-8844-12c93bb66285");
                _loginusernameInfo = new RepoItemInfo(this, "LoginUsername", ".//input[#'login_username']", 30000, null, "f357fa53-de66-4bc6-adcb-c4468e3a4ec0");
                _loginapplybuttonInfo = new RepoItemInfo(this, "LoginApplyButton", ".//button[#'login_applyButton']", 30000, null, "4a10d058-bb72-4a32-ab26-b56c3a0c5282");
                _loginpasswordInfo = new RepoItemInfo(this, "LoginPassword", ".//input[#'login_password']", 30000, null, "ba64f708-3983-4c1b-bee1-8c60e98a4433");
                _datacollectionwidgetcheckboxcompleteInfo = new DataCollectionWidgetCheckboxCompleteInfoClass(this);
                _addsubjectInfo = new RepoItemInfo(this, "AddSubject", ".//button[#'studyBaseWidget_buttonCreateAdd']", 30000, null, "3b54ddb5-8585-49fe-92e8-cbcc70b6dc13");
                _sitesbuttonInfo = new RepoItemInfo(this, "SitesButton", ".//button[#'enrollWidget_comboSites_button']", 30000, null, "9328280c-2573-49e2-a45f-27e9635d479a");
                _selectsiteInfo = new RepoItemInfo(this, "selectSite", ".//a[@innertext~'2019']", 30000, null, "dead8fc1-6d55-4ecd-98eb-e5dc5365356e");
                _subjectnumberInfo = new RepoItemInfo(this, "SubjectNumber", ".//input[#'enrollWidget_textSubjectNumber']", 30000, null, "ed816dba-2dec-41ab-b191-edc9d053b81b");
                _saveandenterdatabuttonInfo = new RepoItemInfo(this, "SaveAndEnterDataButton", ".//span[@innertext='Save and Enter Data']", 30000, null, "e09f0e9e-96f1-4788-bcbe-285c0983e4e3");
            }

            /// <summary>
            /// The DataCollectionWidgetCheckboxCompleteInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("f19e443a-dd21-4b96-8482-9449fbbd0ff5")]
            public class DataCollectionWidgetCheckboxCompleteInfoClass : RepoItemInfo
            {
                /// <summary>
                /// DataCollectionWidgetCheckboxCompleteInfoClass class constructor.
                /// </summary>
                public DataCollectionWidgetCheckboxCompleteInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "DataCollectionWidgetCheckboxComplete", ".//i[#'dataCollectionWidget_checkboxComplete']", 30000, null, "f19e443a-dd21-4b96-8482-9449fbbd0ff5")
                { }

                /// <summary>
                /// Gets the Checked item image.
                /// </summary>
                /// <returns>The Checked image.</returns>
                [RepositoryImage("8b353992-8df1-48f6-b2fa-36794b2f0a60")]
                public CompressedImage GetChecked()
                {
                    return GetImage("8b353992-8df1-48f6-b2fa-36794b2f0a60");
                }

                /// <summary>
                /// Gets the Checked item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("8b353992-8df1-48f6-b2fa-36794b2f0a60")]
                public CompressedImage GetChecked(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("8b353992-8df1-48f6-b2fa-36794b2f0a60", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8c57a700-52e3-43b0-bb42-688fd9e5c8b2")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8c57a700-52e3-43b0-bb42-688fd9e5c8b2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SearchStudyInRCC item.
            /// </summary>
            [RepositoryItem("1aaeabd0-d27c-4203-9346-f994a87bad37")]
            public virtual Ranorex.InputTag SearchStudyInRCC
            {
                get
                {
                    return _searchstudyinrccInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SearchStudyInRCC item info.
            /// </summary>
            [RepositoryItemInfo("1aaeabd0-d27c-4203-9346-f994a87bad37")]
            public virtual RepoItemInfo SearchStudyInRCCInfo
            {
                get
                {
                    return _searchstudyinrccInfo;
                }
            }

            /// <summary>
            /// The ExistingRCCStudy item.
            /// </summary>
            [RepositoryItem("e497ee0e-507a-42d4-8dbc-21b179383f59")]
            public virtual Ranorex.DivTag ExistingRCCStudy
            {
                get
                {
                    return _existingrccstudyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ExistingRCCStudy item info.
            /// </summary>
            [RepositoryItemInfo("e497ee0e-507a-42d4-8dbc-21b179383f59")]
            public virtual RepoItemInfo ExistingRCCStudyInfo
            {
                get
                {
                    return _existingrccstudyInfo;
                }
            }

            /// <summary>
            /// The ClickSubject item.
            /// </summary>
            [RepositoryItem("e5549fed-7e0e-4f0c-a146-6e802d0e81db")]
            public virtual Ranorex.DivTag ClickSubject
            {
                get
                {
                    return _clicksubjectInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ClickSubject item info.
            /// </summary>
            [RepositoryItemInfo("e5549fed-7e0e-4f0c-a146-6e802d0e81db")]
            public virtual RepoItemInfo ClickSubjectInfo
            {
                get
                {
                    return _clicksubjectInfo;
                }
            }

            /// <summary>
            /// The OpenSubject item.
            /// </summary>
            [RepositoryItem("eae74a37-456a-4128-b4d8-a07f476da351")]
            public virtual Ranorex.DivTag OpenSubject
            {
                get
                {
                    return _opensubjectInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The OpenSubject item info.
            /// </summary>
            [RepositoryItemInfo("eae74a37-456a-4128-b4d8-a07f476da351")]
            public virtual RepoItemInfo OpenSubjectInfo
            {
                get
                {
                    return _opensubjectInfo;
                }
            }

            /// <summary>
            /// The OpenEvent_ item.
            /// </summary>
            [RepositoryItem("e1819309-f7a5-4368-aa69-80d60e74fc27")]
            public virtual Ranorex.DivTag OpenEvent_
            {
                get
                {
                    return _openevent_Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The OpenEvent_ item info.
            /// </summary>
            [RepositoryItemInfo("e1819309-f7a5-4368-aa69-80d60e74fc27")]
            public virtual RepoItemInfo OpenEvent_Info
            {
                get
                {
                    return _openevent_Info;
                }
            }

            /// <summary>
            /// The ClickStartTest item.
            /// </summary>
            [RepositoryItem("fb671e3e-2a1e-498e-897a-9088a17ab693")]
            public virtual Ranorex.DivTag ClickStartTest
            {
                get
                {
                    return _clickstarttestInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ClickStartTest item info.
            /// </summary>
            [RepositoryItemInfo("fb671e3e-2a1e-498e-897a-9088a17ab693")]
            public virtual RepoItemInfo ClickStartTestInfo
            {
                get
                {
                    return _clickstarttestInfo;
                }
            }

            /// <summary>
            /// The BeginAssessment item.
            /// </summary>
            [RepositoryItem("0e9fb7e7-6075-4e54-adef-cd32527d42cc")]
            public virtual Ranorex.SpanTag BeginAssessment
            {
                get
                {
                    return _beginassessmentInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The BeginAssessment item info.
            /// </summary>
            [RepositoryItemInfo("0e9fb7e7-6075-4e54-adef-cd32527d42cc")]
            public virtual RepoItemInfo BeginAssessmentInfo
            {
                get
                {
                    return _beginassessmentInfo;
                }
            }

            /// <summary>
            /// The ClcikYes item.
            /// </summary>
            [RepositoryItem("fa7f40ce-5cb8-4540-9101-1575b6fd6412")]
            public virtual Ranorex.SpanTag ClcikYes
            {
                get
                {
                    return _clcikyesInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ClcikYes item info.
            /// </summary>
            [RepositoryItemInfo("fa7f40ce-5cb8-4540-9101-1575b6fd6412")]
            public virtual RepoItemInfo ClcikYesInfo
            {
                get
                {
                    return _clcikyesInfo;
                }
            }

            /// <summary>
            /// The CompositeOutcome item.
            /// </summary>
            [RepositoryItem("c30cba75-1d90-4d95-8844-12c93bb66285")]
            public virtual Ranorex.DivTag CompositeOutcome
            {
                get
                {
                    return _compositeoutcomeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CompositeOutcome item info.
            /// </summary>
            [RepositoryItemInfo("c30cba75-1d90-4d95-8844-12c93bb66285")]
            public virtual RepoItemInfo CompositeOutcomeInfo
            {
                get
                {
                    return _compositeoutcomeInfo;
                }
            }

            /// <summary>
            /// The LoginUsername item.
            /// </summary>
            [RepositoryItem("f357fa53-de66-4bc6-adcb-c4468e3a4ec0")]
            public virtual Ranorex.InputTag LoginUsername
            {
                get
                {
                    return _loginusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginUsername item info.
            /// </summary>
            [RepositoryItemInfo("f357fa53-de66-4bc6-adcb-c4468e3a4ec0")]
            public virtual RepoItemInfo LoginUsernameInfo
            {
                get
                {
                    return _loginusernameInfo;
                }
            }

            /// <summary>
            /// The LoginApplyButton item.
            /// </summary>
            [RepositoryItem("4a10d058-bb72-4a32-ab26-b56c3a0c5282")]
            public virtual Ranorex.ButtonTag LoginApplyButton
            {
                get
                {
                    return _loginapplybuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The LoginApplyButton item info.
            /// </summary>
            [RepositoryItemInfo("4a10d058-bb72-4a32-ab26-b56c3a0c5282")]
            public virtual RepoItemInfo LoginApplyButtonInfo
            {
                get
                {
                    return _loginapplybuttonInfo;
                }
            }

            /// <summary>
            /// The LoginPassword item.
            /// </summary>
            [RepositoryItem("ba64f708-3983-4c1b-bee1-8c60e98a4433")]
            public virtual Ranorex.InputTag LoginPassword
            {
                get
                {
                    return _loginpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginPassword item info.
            /// </summary>
            [RepositoryItemInfo("ba64f708-3983-4c1b-bee1-8c60e98a4433")]
            public virtual RepoItemInfo LoginPasswordInfo
            {
                get
                {
                    return _loginpasswordInfo;
                }
            }

            /// <summary>
            /// The DataCollectionWidgetCheckboxComplete item.
            /// </summary>
            [RepositoryItem("f19e443a-dd21-4b96-8482-9449fbbd0ff5")]
            public virtual Ranorex.ITag DataCollectionWidgetCheckboxComplete
            {
                get
                {
                    return _datacollectionwidgetcheckboxcompleteInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The DataCollectionWidgetCheckboxComplete item info.
            /// </summary>
            [RepositoryItemInfo("f19e443a-dd21-4b96-8482-9449fbbd0ff5")]
            public virtual DataCollectionWidgetCheckboxCompleteInfoClass DataCollectionWidgetCheckboxCompleteInfo
            {
                get
                {
                    return _datacollectionwidgetcheckboxcompleteInfo;
                }
            }

            /// <summary>
            /// The AddSubject item.
            /// </summary>
            [RepositoryItem("3b54ddb5-8585-49fe-92e8-cbcc70b6dc13")]
            public virtual Ranorex.ButtonTag AddSubject
            {
                get
                {
                    return _addsubjectInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddSubject item info.
            /// </summary>
            [RepositoryItemInfo("3b54ddb5-8585-49fe-92e8-cbcc70b6dc13")]
            public virtual RepoItemInfo AddSubjectInfo
            {
                get
                {
                    return _addsubjectInfo;
                }
            }

            /// <summary>
            /// The SitesButton item.
            /// </summary>
            [RepositoryItem("9328280c-2573-49e2-a45f-27e9635d479a")]
            public virtual Ranorex.ButtonTag SitesButton
            {
                get
                {
                    return _sitesbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SitesButton item info.
            /// </summary>
            [RepositoryItemInfo("9328280c-2573-49e2-a45f-27e9635d479a")]
            public virtual RepoItemInfo SitesButtonInfo
            {
                get
                {
                    return _sitesbuttonInfo;
                }
            }

            /// <summary>
            /// The selectSite item.
            /// </summary>
            [RepositoryItem("dead8fc1-6d55-4ecd-98eb-e5dc5365356e")]
            public virtual Ranorex.ATag selectSite
            {
                get
                {
                    return _selectsiteInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The selectSite item info.
            /// </summary>
            [RepositoryItemInfo("dead8fc1-6d55-4ecd-98eb-e5dc5365356e")]
            public virtual RepoItemInfo selectSiteInfo
            {
                get
                {
                    return _selectsiteInfo;
                }
            }

            /// <summary>
            /// The SubjectNumber item.
            /// </summary>
            [RepositoryItem("ed816dba-2dec-41ab-b191-edc9d053b81b")]
            public virtual Ranorex.InputTag SubjectNumber
            {
                get
                {
                    return _subjectnumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubjectNumber item info.
            /// </summary>
            [RepositoryItemInfo("ed816dba-2dec-41ab-b191-edc9d053b81b")]
            public virtual RepoItemInfo SubjectNumberInfo
            {
                get
                {
                    return _subjectnumberInfo;
                }
            }

            /// <summary>
            /// The SaveAndEnterDataButton item.
            /// </summary>
            [RepositoryItem("e09f0e9e-96f1-4788-bcbe-285c0983e4e3")]
            public virtual Ranorex.SpanTag SaveAndEnterDataButton
            {
                get
                {
                    return _saveandenterdatabuttonInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SaveAndEnterDataButton item info.
            /// </summary>
            [RepositoryItemInfo("e09f0e9e-96f1-4788-bcbe-285c0983e4e3")]
            public virtual RepoItemInfo SaveAndEnterDataButtonInfo
            {
                get
                {
                    return _saveandenterdatabuttonInfo;
                }
            }
        }

        /// <summary>
        /// The LeaveSiteAppFolder folder.
        /// </summary>
        [RepositoryFolder("67e4e3c1-b80e-4916-ac48-42c2ed4dae8b")]
        public partial class LeaveSiteAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _leaveInfo;

            /// <summary>
            /// Creates a new LeaveSite  folder.
            /// </summary>
            public LeaveSiteAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LeaveSite", "/form[@title='Leave site?']", parentFolder, 30000, null, true, "67e4e3c1-b80e-4916-ac48-42c2ed4dae8b", "")
            {
                _leaveInfo = new RepoItemInfo(this, "Leave", "container[@accessiblename='']//button[@accessiblename='Leave']", 30000, null, "6cc905b8-3b2a-42c7-a7b1-d4088aad6607");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("67e4e3c1-b80e-4916-ac48-42c2ed4dae8b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("67e4e3c1-b80e-4916-ac48-42c2ed4dae8b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Leave item.
            /// </summary>
            [RepositoryItem("6cc905b8-3b2a-42c7-a7b1-d4088aad6607")]
            public virtual Ranorex.Button Leave
            {
                get
                {
                    return _leaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Leave item info.
            /// </summary>
            [RepositoryItemInfo("6cc905b8-3b2a-42c7-a7b1-d4088aad6607")]
            public virtual RepoItemInfo LeaveInfo
            {
                get
                {
                    return _leaveInfo;
                }
            }
        }

        /// <summary>
        /// The SignInAppFolder folder.
        /// </summary>
        [RepositoryFolder("29fb0691-ee86-4289-abe1-a78470d5da1d")]
        public partial class SignInAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _passwordinputInfo;
            RepoItemInfo _submitbuttonInfo;

            /// <summary>
            /// Creates a new SignIn  folder.
            /// </summary>
            public SignInAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SignIn", "/dom[@domain='login.cogstate.com']", parentFolder, 30000, null, false, "29fb0691-ee86-4289-abe1-a78470d5da1d", "")
            {
                _passwordinputInfo = new RepoItemInfo(this, "PasswordInput", ".//input[#'passwordInput']", 30000, null, "6f77d72f-6ee7-44c9-ba1d-66990d0876c6");
                _submitbuttonInfo = new RepoItemInfo(this, "SubmitButton", ".//span[#'submitButton']", 30000, null, "b35f274a-818c-48ad-9a9d-770748bd0a29");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("29fb0691-ee86-4289-abe1-a78470d5da1d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("29fb0691-ee86-4289-abe1-a78470d5da1d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PasswordInput item.
            /// </summary>
            [RepositoryItem("6f77d72f-6ee7-44c9-ba1d-66990d0876c6")]
            public virtual Ranorex.InputTag PasswordInput
            {
                get
                {
                    return _passwordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("6f77d72f-6ee7-44c9-ba1d-66990d0876c6")]
            public virtual RepoItemInfo PasswordInputInfo
            {
                get
                {
                    return _passwordinputInfo;
                }
            }

            /// <summary>
            /// The SubmitButton item.
            /// </summary>
            [RepositoryItem("b35f274a-818c-48ad-9a9d-770748bd0a29")]
            public virtual Ranorex.SpanTag SubmitButton
            {
                get
                {
                    return _submitbuttonInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("b35f274a-818c-48ad-9a9d-770748bd0a29")]
            public virtual RepoItemInfo SubmitButtonInfo
            {
                get
                {
                    return _submitbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The SignInToYourAccountAppFolder folder.
        /// </summary>
        [RepositoryFolder("e1e54a0b-d167-4616-8313-fb55e887a8fc")]
        public partial class SignInToYourAccountAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _idbtnbackInfo;
            RepoItemInfo _enterusenameInfo;
            RepoItemInfo _clicknextInfo;
            RepoItemInfo _selectaccountInfo;
            RepoItemInfo _useanotheraccountInfo;

            /// <summary>
            /// Creates a new SignInToYourAccount  folder.
            /// </summary>
            public SignInToYourAccountAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SignInToYourAccount", "/dom[@domain='login.microsoftonline.com']", parentFolder, 30000, null, false, "e1e54a0b-d167-4616-8313-fb55e887a8fc", "")
            {
                _idbtnbackInfo = new RepoItemInfo(this, "IdBtnBack", ".//input[#'idBtn_Back']", 30000, null, "5b16e7df-2bc8-408d-a90f-a12b6cf5b5ef");
                _enterusenameInfo = new RepoItemInfo(this, "EnterUseName", ".//input[#'i0116']", 30000, null, "c2b76402-5b3d-43ee-8e59-dac47a2e9c73");
                _clicknextInfo = new RepoItemInfo(this, "ClickNext", ".//input[#'idSIButton9']", 30000, null, "cb220122-19c8-4bab-93a1-825edc6f60eb");
                _selectaccountInfo = new RepoItemInfo(this, "SelectAccount", ".//div[@innertext=$CSPUsername]", 30000, null, "76cba7cf-f54a-4c20-8edb-614644e18a77");
                _useanotheraccountInfo = new RepoItemInfo(this, "UseAnotherAccount", ".//div[#'otherTileText']", 30000, null, "03048239-ba3c-4e99-98f0-7a29857dc2f3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e1e54a0b-d167-4616-8313-fb55e887a8fc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e1e54a0b-d167-4616-8313-fb55e887a8fc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IdBtnBack item.
            /// </summary>
            [RepositoryItem("5b16e7df-2bc8-408d-a90f-a12b6cf5b5ef")]
            public virtual Ranorex.InputTag IdBtnBack
            {
                get
                {
                    return _idbtnbackInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The IdBtnBack item info.
            /// </summary>
            [RepositoryItemInfo("5b16e7df-2bc8-408d-a90f-a12b6cf5b5ef")]
            public virtual RepoItemInfo IdBtnBackInfo
            {
                get
                {
                    return _idbtnbackInfo;
                }
            }

            /// <summary>
            /// The EnterUseName item.
            /// </summary>
            [RepositoryItem("c2b76402-5b3d-43ee-8e59-dac47a2e9c73")]
            public virtual Ranorex.InputTag EnterUseName
            {
                get
                {
                    return _enterusenameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EnterUseName item info.
            /// </summary>
            [RepositoryItemInfo("c2b76402-5b3d-43ee-8e59-dac47a2e9c73")]
            public virtual RepoItemInfo EnterUseNameInfo
            {
                get
                {
                    return _enterusenameInfo;
                }
            }

            /// <summary>
            /// The ClickNext item.
            /// </summary>
            [RepositoryItem("cb220122-19c8-4bab-93a1-825edc6f60eb")]
            public virtual Ranorex.InputTag ClickNext
            {
                get
                {
                    return _clicknextInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ClickNext item info.
            /// </summary>
            [RepositoryItemInfo("cb220122-19c8-4bab-93a1-825edc6f60eb")]
            public virtual RepoItemInfo ClickNextInfo
            {
                get
                {
                    return _clicknextInfo;
                }
            }

            /// <summary>
            /// The SelectAccount item.
            /// </summary>
            [RepositoryItem("76cba7cf-f54a-4c20-8edb-614644e18a77")]
            public virtual Ranorex.DivTag SelectAccount
            {
                get
                {
                    return _selectaccountInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SelectAccount item info.
            /// </summary>
            [RepositoryItemInfo("76cba7cf-f54a-4c20-8edb-614644e18a77")]
            public virtual RepoItemInfo SelectAccountInfo
            {
                get
                {
                    return _selectaccountInfo;
                }
            }

            /// <summary>
            /// The UseAnotherAccount item.
            /// </summary>
            [RepositoryItem("03048239-ba3c-4e99-98f0-7a29857dc2f3")]
            public virtual Ranorex.DivTag UseAnotherAccount
            {
                get
                {
                    return _useanotheraccountInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UseAnotherAccount item info.
            /// </summary>
            [RepositoryItemInfo("03048239-ba3c-4e99-98f0-7a29857dc2f3")]
            public virtual RepoItemInfo UseAnotherAccountInfo
            {
                get
                {
                    return _useanotheraccountInfo;
                }
            }
        }

        /// <summary>
        /// The REDCapCloudGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("c3587369-faf2-4be6-a9b8-82cc31d5ad93")]
        public partial class REDCapCloudGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rcc_usernameInfo;

            /// <summary>
            /// Creates a new REDCapCloudGoogleChrome  folder.
            /// </summary>
            public REDCapCloudGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("REDCapCloudGoogleChrome", "/form[@title~'^REDCap\\ Cloud\\ -\\ Google\\ Chr']", parentFolder, 30000, null, true, "c3587369-faf2-4be6-a9b8-82cc31d5ad93", "")
            {
                _rcc_usernameInfo = new RepoItemInfo(this, "RCC_Username", ".//text[@accessiblename='Username']", 30000, null, "5245351e-02ed-495a-ad53-a9cdf6cc7fd0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c3587369-faf2-4be6-a9b8-82cc31d5ad93")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c3587369-faf2-4be6-a9b8-82cc31d5ad93")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RCC_Username item.
            /// </summary>
            [RepositoryItem("5245351e-02ed-495a-ad53-a9cdf6cc7fd0")]
            public virtual Ranorex.Text RCC_Username
            {
                get
                {
                    return _rcc_usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RCC_Username item info.
            /// </summary>
            [RepositoryItemInfo("5245351e-02ed-495a-ad53-a9cdf6cc7fd0")]
            public virtual RepoItemInfo RCC_UsernameInfo
            {
                get
                {
                    return _rcc_usernameInfo;
                }
            }
        }

        /// <summary>
        /// The KuduServicesAppFolder folder.
        /// </summary>
        [RepositoryFolder("83d87542-91e4-4062-831c-e71dae0b7938")]
        public partial class KuduServicesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _debugconsoleInfo;
            RepoItemInfo _powershellInfo;
            RepoItemInfo _powershallconsolInfo;
            RepoItemInfo _azurelogoutInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _dctvalidationversionInfo;
            RepoItemInfo _rcchubvalidationInfo;
            RepoItemInfo _rcc_hubpowershallInfo;

            /// <summary>
            /// Creates a new KuduServices  folder.
            /// </summary>
            public KuduServicesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KuduServices", "/dom[@domain=$AzureDOM]", parentFolder, 30000, null, false, "83d87542-91e4-4062-831c-e71dae0b7938", "")
            {
                _debugconsoleInfo = new RepoItemInfo(this, "DebugConsole", ".//a[@innertext='Debug console ']", 30000, null, "67cbad4f-5b5c-41d7-a22b-8b0b8a2f529d");
                _powershellInfo = new RepoItemInfo(this, "PowerShell", ".//a[@innertext='PowerShell']", 30000, null, "63637764-b1c2-45b3-96c3-243481d396a3");
                _powershallconsolInfo = new RepoItemInfo(this, "PowerShallConsol", ".//div[#'KuduExecConsoleV2']/div/div/div[2]/?/?/span", 30000, null, "cb458012-66d2-43c8-90cf-f9dc911f0576");
                _azurelogoutInfo = new RepoItemInfo(this, "AzureLogout", ".//a[@innertext=$CSPUsername]", 30000, null, "ba6ef5cd-ae29-46fd-a862-13b41632bc4d");
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//a[@innertext='Logout']", 30000, null, "bdad3e06-3e70-4d6e-ab3f-7b4eda7eddae");
                _dctvalidationversionInfo = new RepoItemInfo(this, "DCTValidationVersion", ".//div[@innertext~'1.2']", 30000, null, "49370b0d-946f-4152-89ea-e31cf4c37984");
                _rcchubvalidationInfo = new RepoItemInfo(this, "RCCHubValidation", ".//div[@innertext~'2.0.0-rc']", 30000, null, "ed9435cd-5012-46e1-a260-05d5ba9de604");
                _rcc_hubpowershallInfo = new RepoItemInfo(this, "rcc_hubPowerShall", ".//div[#'KuduExecConsoleV2']/div/div/div[10]/?/?/span", 30000, null, "87776a16-3265-49f0-8531-9f13f44dcc65");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("83d87542-91e4-4062-831c-e71dae0b7938")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("83d87542-91e4-4062-831c-e71dae0b7938")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DebugConsole item.
            /// </summary>
            [RepositoryItem("67cbad4f-5b5c-41d7-a22b-8b0b8a2f529d")]
            public virtual Ranorex.ATag DebugConsole
            {
                get
                {
                    return _debugconsoleInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DebugConsole item info.
            /// </summary>
            [RepositoryItemInfo("67cbad4f-5b5c-41d7-a22b-8b0b8a2f529d")]
            public virtual RepoItemInfo DebugConsoleInfo
            {
                get
                {
                    return _debugconsoleInfo;
                }
            }

            /// <summary>
            /// The PowerShell item.
            /// </summary>
            [RepositoryItem("63637764-b1c2-45b3-96c3-243481d396a3")]
            public virtual Ranorex.ATag PowerShell
            {
                get
                {
                    return _powershellInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The PowerShell item info.
            /// </summary>
            [RepositoryItemInfo("63637764-b1c2-45b3-96c3-243481d396a3")]
            public virtual RepoItemInfo PowerShellInfo
            {
                get
                {
                    return _powershellInfo;
                }
            }

            /// <summary>
            /// The PowerShallConsol item.
            /// </summary>
            [RepositoryItem("cb458012-66d2-43c8-90cf-f9dc911f0576")]
            public virtual Ranorex.SpanTag PowerShallConsol
            {
                get
                {
                    return _powershallconsolInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PowerShallConsol item info.
            /// </summary>
            [RepositoryItemInfo("cb458012-66d2-43c8-90cf-f9dc911f0576")]
            public virtual RepoItemInfo PowerShallConsolInfo
            {
                get
                {
                    return _powershallconsolInfo;
                }
            }

            /// <summary>
            /// The AzureLogout item.
            /// </summary>
            [RepositoryItem("ba6ef5cd-ae29-46fd-a862-13b41632bc4d")]
            public virtual Ranorex.ATag AzureLogout
            {
                get
                {
                    return _azurelogoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AzureLogout item info.
            /// </summary>
            [RepositoryItemInfo("ba6ef5cd-ae29-46fd-a862-13b41632bc4d")]
            public virtual RepoItemInfo AzureLogoutInfo
            {
                get
                {
                    return _azurelogoutInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("bdad3e06-3e70-4d6e-ab3f-7b4eda7eddae")]
            public virtual Ranorex.ATag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("bdad3e06-3e70-4d6e-ab3f-7b4eda7eddae")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The DCTValidationVersion item.
            /// </summary>
            [RepositoryItem("49370b0d-946f-4152-89ea-e31cf4c37984")]
            public virtual Ranorex.DivTag DCTValidationVersion
            {
                get
                {
                    return _dctvalidationversionInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DCTValidationVersion item info.
            /// </summary>
            [RepositoryItemInfo("49370b0d-946f-4152-89ea-e31cf4c37984")]
            public virtual RepoItemInfo DCTValidationVersionInfo
            {
                get
                {
                    return _dctvalidationversionInfo;
                }
            }

            /// <summary>
            /// The RCCHubValidation item.
            /// </summary>
            [RepositoryItem("ed9435cd-5012-46e1-a260-05d5ba9de604")]
            public virtual Ranorex.DivTag RCCHubValidation
            {
                get
                {
                    return _rcchubvalidationInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The RCCHubValidation item info.
            /// </summary>
            [RepositoryItemInfo("ed9435cd-5012-46e1-a260-05d5ba9de604")]
            public virtual RepoItemInfo RCCHubValidationInfo
            {
                get
                {
                    return _rcchubvalidationInfo;
                }
            }

            /// <summary>
            /// The rcc_hubPowerShall item.
            /// </summary>
            [RepositoryItem("87776a16-3265-49f0-8531-9f13f44dcc65")]
            public virtual Ranorex.SpanTag rcc_hubPowerShall
            {
                get
                {
                    return _rcc_hubpowershallInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The rcc_hubPowerShall item info.
            /// </summary>
            [RepositoryItemInfo("87776a16-3265-49f0-8531-9f13f44dcc65")]
            public virtual RepoItemInfo rcc_hubPowerShallInfo
            {
                get
                {
                    return _rcc_hubpowershallInfo;
                }
            }
        }

        /// <summary>
        /// The CogstateSolutionPlatformAppFolder folder.
        /// </summary>
        [RepositoryFolder("38465dbb-2a52-4f97-a7da-4f756315b3f4")]
        public partial class CogstateSolutionPlatformAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _academicextractInfo;
            RepoItemInfo _reportstabInfo;

            /// <summary>
            /// Creates a new CogstateSolutionPlatform  folder.
            /// </summary>
            public CogstateSolutionPlatformAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CogstateSolutionPlatform", "/dom[@domain=$CSPDOM]", parentFolder, 30000, null, false, "38465dbb-2a52-4f97-a7da-4f756315b3f4", "")
            {
                _academicextractInfo = new RepoItemInfo(this, "AcademicExtract", ".//a[@innertext='Academic Extract']", 30000, null, "5f95c61a-732b-463d-a24a-1847574f6cd8");
                _reportstabInfo = new RepoItemInfo(this, "ReportsTab", ".//a[@innertext='Reports']", 30000, null, "93211f96-5811-43a7-b78f-36c0459fd008");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("38465dbb-2a52-4f97-a7da-4f756315b3f4")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("38465dbb-2a52-4f97-a7da-4f756315b3f4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AcademicExtract item.
            /// </summary>
            [RepositoryItem("5f95c61a-732b-463d-a24a-1847574f6cd8")]
            public virtual Ranorex.ATag AcademicExtract
            {
                get
                {
                    return _academicextractInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AcademicExtract item info.
            /// </summary>
            [RepositoryItemInfo("5f95c61a-732b-463d-a24a-1847574f6cd8")]
            public virtual RepoItemInfo AcademicExtractInfo
            {
                get
                {
                    return _academicextractInfo;
                }
            }

            /// <summary>
            /// The ReportsTab item.
            /// </summary>
            [RepositoryItem("93211f96-5811-43a7-b78f-36c0459fd008")]
            public virtual Ranorex.ATag ReportsTab
            {
                get
                {
                    return _reportstabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ReportsTab item info.
            /// </summary>
            [RepositoryItemInfo("93211f96-5811-43a7-b78f-36c0459fd008")]
            public virtual RepoItemInfo ReportsTabInfo
            {
                get
                {
                    return _reportstabInfo;
                }
            }
        }

        /// <summary>
        /// The AcademicExtractOrrPowerBIAppFolder folder.
        /// </summary>
        [RepositoryFolder("f1e3226f-4e04-44a6-8973-7f7dc740f469")]
        public partial class AcademicExtractOrrPowerBIAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _protocolidInfo;

            /// <summary>
            /// Creates a new AcademicExtractOrrPowerBI  folder.
            /// </summary>
            public AcademicExtractOrrPowerBIAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AcademicExtractOrrPowerBI", "/dom[@domain='app.powerbi.com']", parentFolder, 30000, null, false, "f1e3226f-4e04-44a6-8973-7f7dc740f469", "")
            {
                _protocolidInfo = new RepoItemInfo(this, "ProtocolID", ".//div[@title='ProtocolID']", 30000, null, "f8c22779-29ad-4dfc-a968-f2174074c356");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f1e3226f-4e04-44a6-8973-7f7dc740f469")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f1e3226f-4e04-44a6-8973-7f7dc740f469")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProtocolID item.
            /// </summary>
            [RepositoryItem("f8c22779-29ad-4dfc-a968-f2174074c356")]
            public virtual Ranorex.DivTag ProtocolID
            {
                get
                {
                    return _protocolidInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ProtocolID item info.
            /// </summary>
            [RepositoryItemInfo("f8c22779-29ad-4dfc-a968-f2174074c356")]
            public virtual RepoItemInfo ProtocolIDInfo
            {
                get
                {
                    return _protocolidInfo;
                }
            }
        }

        /// <summary>
        /// The REDCapCloud1AppFolder folder.
        /// </summary>
        [RepositoryFolder("ee5f1b78-cba3-4623-b016-bbed2259c88e")]
        public partial class REDCapCloud1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _studynameInfo;
            RepoItemInfo _entersubjectnumberInfo;

            /// <summary>
            /// Creates a new REDCapCloud1  folder.
            /// </summary>
            public REDCapCloud1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("REDCapCloud1", "/dom[@domain='cgsqc.redcapcloud.com']", parentFolder, 30000, null, false, "ee5f1b78-cba3-4623-b016-bbed2259c88e", "")
            {
                _studynameInfo = new RepoItemInfo(this, "StudyName", ".//div[@innertext~'2019']", 30000, null, "8a110e17-ca00-4f2c-b6ba-ef4ffcf8fe48");
                _entersubjectnumberInfo = new RepoItemInfo(this, "EnterSubjectNumber", ".//input[#'enrollWidget_textSubjectNumber']", 30000, null, "972775f8-a766-4c55-8ce5-b63405dd6144");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ee5f1b78-cba3-4623-b016-bbed2259c88e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ee5f1b78-cba3-4623-b016-bbed2259c88e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The StudyName item.
            /// </summary>
            [RepositoryItem("8a110e17-ca00-4f2c-b6ba-ef4ffcf8fe48")]
            public virtual Ranorex.DivTag StudyName
            {
                get
                {
                    return _studynameInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The StudyName item info.
            /// </summary>
            [RepositoryItemInfo("8a110e17-ca00-4f2c-b6ba-ef4ffcf8fe48")]
            public virtual RepoItemInfo StudyNameInfo
            {
                get
                {
                    return _studynameInfo;
                }
            }

            /// <summary>
            /// The EnterSubjectNumber item.
            /// </summary>
            [RepositoryItem("972775f8-a766-4c55-8ce5-b63405dd6144")]
            public virtual Ranorex.InputTag EnterSubjectNumber
            {
                get
                {
                    return _entersubjectnumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EnterSubjectNumber item info.
            /// </summary>
            [RepositoryItemInfo("972775f8-a766-4c55-8ce5-b63405dd6144")]
            public virtual RepoItemInfo EnterSubjectNumberInfo
            {
                get
                {
                    return _entersubjectnumberInfo;
                }
            }
        }

        /// <summary>
        /// The DataCleaningTool1AppFolder folder.
        /// </summary>
        [RepositoryFolder("c999cc24-7711-432b-bcf1-273bdadd7e3f")]
        public partial class DataCleaningTool1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _findbyassessmentidInfo;

            /// <summary>
            /// Creates a new DataCleaningTool1  folder.
            /// </summary>
            public DataCleaningTool1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("DataCleaningTool1", "/dom[@domain='cgst-qc-orr-dct.azurewebsites.net']", parentFolder, 30000, null, false, "c999cc24-7711-432b-bcf1-273bdadd7e3f", "")
            {
                _findbyassessmentidInfo = new RepoItemInfo(this, "FindByAssessmentId", ".//input[#'findByAssessmentId']", 30000, null, "51fcbb6e-5900-4e52-8e6a-d043a82b497d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c999cc24-7711-432b-bcf1-273bdadd7e3f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c999cc24-7711-432b-bcf1-273bdadd7e3f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FindByAssessmentId item.
            /// </summary>
            [RepositoryItem("51fcbb6e-5900-4e52-8e6a-d043a82b497d")]
            public virtual Ranorex.InputTag FindByAssessmentId
            {
                get
                {
                    return _findbyassessmentidInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FindByAssessmentId item info.
            /// </summary>
            [RepositoryItemInfo("51fcbb6e-5900-4e52-8e6a-d043a82b497d")]
            public virtual RepoItemInfo FindByAssessmentIdInfo
            {
                get
                {
                    return _findbyassessmentidInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}