///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Processor
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ProcessorRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("0e62f402-82bf-43c0-975c-3135961bc893")]
    public partial class ProcessorRepository : RepoGenBaseFolder
    {
        static ProcessorRepository instance = new ProcessorRepository();

        /// <summary>
        /// Gets the singleton class instance representing the ProcessorRepository element repository.
        /// </summary>
        [RepositoryFolder("0e62f402-82bf-43c0-975c-3135961bc893")]
        public static ProcessorRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ProcessorRepository() 
            : base("ProcessorRepository", "/", null, 0, false, "0e62f402-82bf-43c0-975c-3135961bc893", ".\\RepositoryImages\\ProcessorRepository0e62f402.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0e62f402-82bf-43c0-975c-3135961bc893")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class ProcessorRepositoryFolders
    {
    }
#pragma warning restore 0436
}