///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DCT.Single_Sign_In
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectUserName recording.
    /// </summary>
    [TestModule("366ec434-a4de-4276-9c8c-e6703eef9698", ModuleType.Recording, 1)]
    public partial class SelectUserName : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DCT.DCTRepository repository.
        /// </summary>
        public static global::DCT.DCTRepository repo = global::DCT.DCTRepository.Instance;

        static SelectUserName instance = new SelectUserName();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectUserName()
        {
            CPAUsername = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectUserName Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable CPAUsername.
        /// </summary>
        [TestVariable("08bcae22-9936-418c-853d-2a82e345cf1c")]
        public string CPAUsername
        {
            get { return repo.CPAUsername; }
            set { repo.CPAUsername = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInToYourAccount.SelectAccount' at Center.", repo.SignInToYourAccount.SelectAccountInfo, new RecordItemIndex(0));
            //repo.SignInToYourAccount.SelectAccount.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 800ms.", new RecordItemIndex(1));
            Delay.Duration(800, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SignInToYourAccount.UseAnotherAccount' at Center.", repo.SignInToYourAccount.UseAnotherAccountInfo, new RecordItemIndex(2));
            //repo.SignInToYourAccount.UseAnotherAccount.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CPAUsername' with focus on 'SignInToYourAccount.EnterUserNameField'.", repo.SignInToYourAccount.EnterUserNameFieldInfo, new RecordItemIndex(3));
            //repo.SignInToYourAccount.EnterUserNameField.PressKeys(CPAUsername);
            //Delay.Milliseconds(0);
            
            Mouse_Click_EnterUseName(repo.SignInToYourAccount.EnterUserNameFieldInfo);
            Delay.Milliseconds(0);
            
            Key_sequence_EnterUseName(repo.SignInToYourAccount.EnterUserNameFieldInfo);
            Delay.Milliseconds(0);
            
            Mouse_Click_ClickNext(repo.SignInToYourAccount.SignInButtonInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
