///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Eisia
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SecretKey recording.
    /// </summary>
    [TestModule("64cee487-0f3b-4427-8ac6-746384f3aa0b", ModuleType.Recording, 1)]
    public partial class SecretKey : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EisiaRepository repository.
        /// </summary>
        public static EisiaRepository repo = EisiaRepository.Instance;

        static SecretKey instance = new SecretKey();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SecretKey()
        {
            DOM = "";
            RestToken = "";
            Token = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SecretKey Instance
        {
            get { return instance; }
        }

#region Variables

        string _DOM;

        /// <summary>
        /// Gets or sets the value of variable DOM.
        /// </summary>
        [TestVariable("bf4e42d1-b3c0-44df-b330-aa3b0618f1fc")]
        public string DOM
        {
            get { return _DOM; }
            set { _DOM = value; }
        }

        string _RestToken;

        /// <summary>
        /// Gets or sets the value of variable RestToken.
        /// </summary>
        [TestVariable("785afc36-1f6e-4392-8c52-dd8926052b5c")]
        public string RestToken
        {
            get { return _RestToken; }
            set { _RestToken = value; }
        }

        string _Token;

        /// <summary>
        /// Gets or sets the value of variable Token.
        /// </summary>
        [TestVariable("48d3037b-baaf-4ecb-8370-01301cb89b6f")]
        public string Token
        {
            get { return _Token; }
            set { _Token = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            NewSecretKey(DOM, RestToken);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
