///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PrecisionRecruitment.InputModules
{
    public partial class Add_Role_External_User
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void SelectStudyToAdd()
        {
        	//Wait for list to load (need to change this method)
        	Delay.Duration(30000);
        	
            //click on dropdown to expand the list of Studies Available
        	Report.Log(ReportLevel.Info,"Mouse click on AddRoleStudyDropdown");
        	repo.CogstateSolutionPlatform.ExternalUserPage.AddRoleStudyDropdown.Click();
        		
        	//find the study we want and select it
        	Keyboard.Press(CodeName + RandNum);
        	Thread.Sleep(500);
        	Keyboard.Press("{ENTER}");
        	
        }

        public void SelectExternalServiceRole()
        {
            //click on dropdown to expand the list of Roles Available
        	Report.Log(ReportLevel.Info,"Mouse click on ExternalServiceRoleDropdown");
        	repo.CogstateSolutionPlatform.ExternalUserPage.ExternalServiceRoleDropdown.Click();
        	
        	Keyboard.Press("External Service");
        	Thread.Sleep(500);        	
        	Keyboard.Press("{ENTER}");
        }

    }
}
