///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RedCapCloudAndroid.EventDefinitionsPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Touch_EventDefinitionsTab recording.
    /// </summary>
    [TestModule("fb3b224a-30a9-449b-b906-4da0abd6b63c", ModuleType.Recording, 1)]
    public partial class Touch_EventDefinitionsTab : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RedCapCloudAndroid.RedCapCloudAndroidRepository repository.
        /// </summary>
        public static RedCapCloudAndroid.RedCapCloudAndroidRepository repo = RedCapCloudAndroid.RedCapCloudAndroidRepository.Instance;

        static Touch_EventDefinitionsTab instance = new Touch_EventDefinitionsTab();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Touch_EventDefinitionsTab()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Touch_EventDefinitionsTab Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 100;
            Keyboard.DefaultKeyPressTime = 10;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'RanorexBrowser.Dom.StudyTabs.EventDefinitionsTab' at Center", repo.RanorexBrowser.Dom.StudyTabs.EventDefinitionsTabInfo, new RecordItemIndex(0));
            repo.RanorexBrowser.Dom.StudyTabs.EventDefinitionsTab.Touch();
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
