///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CSP.APIV2Modules
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UB11 recording.
    /// </summary>
    [TestModule("d3463bf2-92a2-4729-b553-1836fdb35ec2", ModuleType.Recording, 1)]
    public partial class UB11 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::CSP.CSPRepository repository.
        /// </summary>
        public static global::CSP.CSPRepository repo = global::CSP.CSPRepository.Instance;

        static UB11 instance = new UB11();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UB11()
        {
            workflowID = "";
            DOM = "";
            workflowToken = "";
            Batteryid = "";
            rawdata = "";
            assessmentID = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UB11 Instance
        {
            get { return instance; }
        }

#region Variables

        string _workflowID;

        /// <summary>
        /// Gets or sets the value of variable workflowID.
        /// </summary>
        [TestVariable("e48f0ee2-f789-4dce-981c-333c0247b775")]
        public string workflowID
        {
            get { return _workflowID; }
            set { _workflowID = value; }
        }

        string _DOM;

        /// <summary>
        /// Gets or sets the value of variable DOM.
        /// </summary>
        [TestVariable("ce0839ea-718f-4cae-b33c-00ba265460a4")]
        public string DOM
        {
            get { return _DOM; }
            set { _DOM = value; }
        }

        string _workflowToken;

        /// <summary>
        /// Gets or sets the value of variable workflowToken.
        /// </summary>
        [TestVariable("460c2981-d575-4ab9-a44b-811624543e97")]
        public string workflowToken
        {
            get { return _workflowToken; }
            set { _workflowToken = value; }
        }

        string _Batteryid;

        /// <summary>
        /// Gets or sets the value of variable Batteryid.
        /// </summary>
        [TestVariable("f79eb44a-e6cb-4a09-bcad-b32aca929272")]
        public string Batteryid
        {
            get { return _Batteryid; }
            set { _Batteryid = value; }
        }

        string _rawdata;

        /// <summary>
        /// Gets or sets the value of variable rawdata.
        /// </summary>
        [TestVariable("91bd15e1-61f8-4d77-8e71-8ce669a8bc7e")]
        public string rawdata
        {
            get { return _rawdata; }
            set { _rawdata = value; }
        }

        string _assessmentID;

        /// <summary>
        /// Gets or sets the value of variable assessmentID.
        /// </summary>
        [TestVariable("dcacb6e1-0d68-4cea-9c2e-62a4e20be89b")]
        public string assessmentID
        {
            get { return _assessmentID; }
            set { _assessmentID = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UpdateBatteryEleven(workflowID, DOM, workflowToken, Batteryid, rawdata);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
