///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RedCapCloud.SubjectsPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Select_Event_and_Add recording.
    /// </summary>
    [TestModule("7a8c2b04-976e-4e4f-8606-dc25f9286a53", ModuleType.Recording, 1)]
    public partial class Select_Event_and_Add : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RedCapCloud.RedCapCloudRepository repository.
        /// </summary>
        public static global::RedCapCloud.RedCapCloudRepository repo = global::RedCapCloud.RedCapCloudRepository.Instance;

        static Select_Event_and_Add instance = new Select_Event_and_Add();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Select_Event_and_Add()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Select_Event_and_Add Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable DOM.
        /// </summary>
        [TestVariable("6f24cf1a-0e47-4c45-9ce6-3e042db234d2")]
        public string DOM
        {
            get { return repo.DOM; }
            set { repo.DOM = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable EventDefName.
        /// </summary>
        [TestVariable("11da9ff3-46e5-4db0-8f94-1b1b60cecde6")]
        public string EventDefName
        {
            get { return repo.EventDefName; }
            set { repo.EventDefName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'REDCapCloud.SubjectsPage.EventNameDropdown' at Center.", repo.REDCapCloud.SubjectsPage.EventNameDropdownInfo, new RecordItemIndex(0));
            repo.REDCapCloud.SubjectsPage.EventNameDropdown.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'REDCapCloud.SubjectsPage.VisitDropdownOption' at Center.", repo.REDCapCloud.SubjectsPage.VisitDropdownOptionInfo, new RecordItemIndex(1));
            repo.REDCapCloud.SubjectsPage.VisitDropdownOption.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'REDCapCloud.SaveAndExit' at Center.", repo.REDCapCloud.SaveAndExitInfo, new RecordItemIndex(2));
            repo.REDCapCloud.SaveAndExit.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1.5s.", new RecordItemIndex(3));
            Delay.Duration(1500, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
