///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CPA.AddVisitSchedulePage
{
    public partial class Add_Visit_to_Schedule
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }


        public void SelectVisitScheduleVisitStatus()
        {
            //click on dropdown to expand the list of Visit Status
        	Report.Log(ReportLevel.Info,"Mouse click on VisitScheduleVisitStatus");
        	repo.CogstateSolutionPlatform.AddVisitSchedulePage.VisitScheduleVisitStatusDropdown.Click();
        		
        	//find the Status we want and select it
        	OptionTag option = "/dom[@domain='" + CPADOM + "']//select[@id~'formly_[0-9]+_select_visitStatus_3']//option[@InnerText='Draft']";
        	option.Focus();
        	option.Selected = true;
        	Keyboard.Press("{ENTER}");
        }

    }
}
