///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PrecisionRecruitmentAndroid.StudiesPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Select_Study recording.
    /// </summary>
    [TestModule("a951f3ef-804d-4c3b-bc95-3371c81f4f3a", ModuleType.Recording, 1)]
    public partial class Select_Study : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PrecisionRecruitmentAndroid.PrecisionRecruitmentAndroidRepository repository.
        /// </summary>
        public static PrecisionRecruitmentAndroid.PrecisionRecruitmentAndroidRepository repo = PrecisionRecruitmentAndroid.PrecisionRecruitmentAndroidRepository.Instance;

        static Select_Study instance = new Select_Study();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Select_Study()
        {
            RandNum = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Select_Study Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable RandNum.
        /// </summary>
        [TestVariable("80f7b88b-be7b-494b-9c00-bd9416daeb57")]
        public string RandNum
        {
            get { return repo.RandNum; }
            set { repo.RandNum = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable URL.
        /// </summary>
        [TestVariable("910026b7-6a0e-4c09-ac0d-34de0e6ef736")]
        public string URL
        {
            get { return repo.URL; }
            set { repo.URL = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 100;
            Keyboard.DefaultKeyPressTime = 10;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'RanorexBrowser.Dom.SimpleDropdown' at Center", repo.RanorexBrowser.Dom.SimpleDropdownInfo, new RecordItemIndex(0));
            repo.RanorexBrowser.Dom.SimpleDropdown.Touch();
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'RanorexBrowser.Dom.StudiesMenuOption' at Center", repo.RanorexBrowser.Dom.StudiesMenuOptionInfo, new RecordItemIndex(1));
            repo.RanorexBrowser.Dom.StudiesMenuOption.Touch();
            Delay.Milliseconds(100);
            
            Try_Enter_StudyName();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'RanorexBrowser.Dom.MainToobar.CardButton' at Center", repo.RanorexBrowser.Dom.MainToobar.CardButtonInfo, new RecordItemIndex(4));
            repo.RanorexBrowser.Dom.MainToobar.CardButton.Touch();
            Delay.Milliseconds(100);
            
            Try_Click_StudyCardTitle();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
