///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DCT.RCC_Page
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VersionValidation recording.
    /// </summary>
    [TestModule("497347f5-f94c-4c1b-adad-bee095e10467", ModuleType.Recording, 1)]
    public partial class VersionValidation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DCT.DCTRepository repository.
        /// </summary>
        public static global::DCT.DCTRepository repo = global::DCT.DCTRepository.Instance;

        static VersionValidation instance = new VersionValidation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VersionValidation()
        {
            DCT_Version = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VersionValidation Instance
        {
            get { return instance; }
        }

#region Variables

        string _DCT_Version;

        /// <summary>
        /// Gets or sets the value of variable DCT_Version.
        /// </summary>
        [TestVariable("3e84eaa1-aaee-49f4-b4c6-dd4aee9b1ddb")]
        public string DCT_Version
        {
            get { return _DCT_Version; }
            set { _DCT_Version = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OctopusDeploy.DCT_VersionValidation' at Center.", repo.OctopusDeploy.DCT_VersionValidationInfo, new RecordItemIndex(0));
            //repo.OctopusDeploy.DCT_VersionValidation.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$DCT_Version) on item 'OctopusDeploy.DCT_VersionValidation'.", repo.OctopusDeploy.DCT_VersionValidationInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.OctopusDeploy.DCT_VersionValidationInfo, "InnerText", DCT_Version);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.OctopusDeploy.DCT_VersionValidation, false, new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
