///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace eSourcePlatform
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the eSourcePlatformRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("d677fdb9-00e1-4467-9fce-a84c063e8bd0")]
    public partial class eSourcePlatformRepository : RepoGenBaseFolder
    {
        static eSourcePlatformRepository instance = new eSourcePlatformRepository();
        eSourcePlatformRepositoryFolders.SignInToYourAccountAppFolder _signintoyouraccount;
        eSourcePlatformRepositoryFolders.SignInAppFolder _signin;
        eSourcePlatformRepositoryFolders.KuduServicesAppFolder _kuduservices;
        eSourcePlatformRepositoryFolders.DiagnosticConsoleAppFolder _diagnosticconsole;

        /// <summary>
        /// Gets the singleton class instance representing the eSourcePlatformRepository element repository.
        /// </summary>
        [RepositoryFolder("d677fdb9-00e1-4467-9fce-a84c063e8bd0")]
        public static eSourcePlatformRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public eSourcePlatformRepository() 
            : base("eSourcePlatformRepository", "/", null, 0, false, "d677fdb9-00e1-4467-9fce-a84c063e8bd0", ".\\RepositoryImages\\eSourcePlatformRepositoryd677fdb9.rximgres")
        {
            _signintoyouraccount = new eSourcePlatformRepositoryFolders.SignInToYourAccountAppFolder(this);
            _signin = new eSourcePlatformRepositoryFolders.SignInAppFolder(this);
            _kuduservices = new eSourcePlatformRepositoryFolders.KuduServicesAppFolder(this);
            _diagnosticconsole = new eSourcePlatformRepositoryFolders.DiagnosticConsoleAppFolder(this);
        }

#region Variables

        string _RandNum = "";

        /// <summary>
        /// Gets or sets the value of variable RandNum.
        /// </summary>
        [TestVariable("879361eb-5136-41f9-be52-87f679719de7")]
        public string RandNum
        {
            get { return _RandNum; }
            set { _RandNum = value; }
        }

        string _CSPUsername = "zchekir@cogstate.com";

        /// <summary>
        /// Gets or sets the value of variable CSPUsername.
        /// </summary>
        [TestVariable("f183ef80-f1e1-40df-acd7-5c4c0e17d549")]
        public string CSPUsername
        {
            get { return _CSPUsername; }
            set { _CSPUsername = value; }
        }

        string _ExistingStudy = "";

        /// <summary>
        /// Gets or sets the value of variable ExistingStudy.
        /// </summary>
        [TestVariable("c7b8c122-f547-448f-a6ca-6da7fbe44867")]
        public string ExistingStudy
        {
            get { return _ExistingStudy; }
            set { _ExistingStudy = value; }
        }

        string _CSPDOM = "cgst-qc-orr.azurewebsites.net";

        /// <summary>
        /// Gets or sets the value of variable CSPDOM.
        /// </summary>
        [TestVariable("7bd16051-5145-48ed-a487-674a71577abf")]
        public string CSPDOM
        {
            get { return _CSPDOM; }
            set { _CSPDOM = value; }
        }

        string _ProtocolID = "";

        /// <summary>
        /// Gets or sets the value of variable ProtocolID.
        /// </summary>
        [TestVariable("64f38c0d-a00b-4a5b-bd53-ba394794cee9")]
        public string ProtocolID
        {
            get { return _ProtocolID; }
            set { _ProtocolID = value; }
        }

        string _AzureDOM = "cgst-qc-orr-hub.scm.azurewebsites.net";

        /// <summary>
        /// Gets or sets the value of variable AzureDOM.
        /// </summary>
        [TestVariable("62431319-fa61-43d0-b7a6-6c7241f54df2")]
        public string AzureDOM
        {
            get { return _AzureDOM; }
            set { _AzureDOM = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d677fdb9-00e1-4467-9fce-a84c063e8bd0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SignInToYourAccount folder.
        /// </summary>
        [RepositoryFolder("c4703fa5-b020-43f6-b7f4-c199f9aebf8b")]
        public virtual eSourcePlatformRepositoryFolders.SignInToYourAccountAppFolder SignInToYourAccount
        {
            get { return _signintoyouraccount; }
        }

        /// <summary>
        /// The SignIn folder.
        /// </summary>
        [RepositoryFolder("df5f0e47-553e-4900-9a01-24ea165a5989")]
        public virtual eSourcePlatformRepositoryFolders.SignInAppFolder SignIn
        {
            get { return _signin; }
        }

        /// <summary>
        /// The KuduServices folder.
        /// </summary>
        [RepositoryFolder("e84fe0dd-7e22-48f7-ad02-07bff40780b9")]
        public virtual eSourcePlatformRepositoryFolders.KuduServicesAppFolder KuduServices
        {
            get { return _kuduservices; }
        }

        /// <summary>
        /// The DiagnosticConsole folder.
        /// </summary>
        [RepositoryFolder("7424d8aa-7302-4ca4-bb9d-70e282c4b92c")]
        public virtual eSourcePlatformRepositoryFolders.DiagnosticConsoleAppFolder DiagnosticConsole
        {
            get { return _diagnosticconsole; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class eSourcePlatformRepositoryFolders
    {
        /// <summary>
        /// The SignInToYourAccountAppFolder folder.
        /// </summary>
        [RepositoryFolder("c4703fa5-b020-43f6-b7f4-c199f9aebf8b")]
        public partial class SignInToYourAccountAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enterusernameInfo;

            /// <summary>
            /// Creates a new SignInToYourAccount  folder.
            /// </summary>
            public SignInToYourAccountAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SignInToYourAccount", "/dom[@domain='login.microsoftonline.com']", parentFolder, 30000, null, false, "c4703fa5-b020-43f6-b7f4-c199f9aebf8b", "")
            {
                _enterusernameInfo = new RepoItemInfo(this, "EnterUsername", ".//div[@innertext=$CSPUsername]", 30000, null, "1205ddd4-2c1f-4adc-b9a6-c358ac98e060");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c4703fa5-b020-43f6-b7f4-c199f9aebf8b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c4703fa5-b020-43f6-b7f4-c199f9aebf8b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterUsername item.
            /// </summary>
            [RepositoryItem("1205ddd4-2c1f-4adc-b9a6-c358ac98e060")]
            public virtual Ranorex.DivTag EnterUsername
            {
                get
                {
                    return _enterusernameInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The EnterUsername item info.
            /// </summary>
            [RepositoryItemInfo("1205ddd4-2c1f-4adc-b9a6-c358ac98e060")]
            public virtual RepoItemInfo EnterUsernameInfo
            {
                get
                {
                    return _enterusernameInfo;
                }
            }
        }

        /// <summary>
        /// The SignInAppFolder folder.
        /// </summary>
        [RepositoryFolder("df5f0e47-553e-4900-9a01-24ea165a5989")]
        public partial class SignInAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _passwordinputInfo;

            /// <summary>
            /// Creates a new SignIn  folder.
            /// </summary>
            public SignInAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SignIn", "/dom[@domain='login.cogstate.com']", parentFolder, 30000, null, false, "df5f0e47-553e-4900-9a01-24ea165a5989", "")
            {
                _passwordinputInfo = new RepoItemInfo(this, "PasswordInput", ".//input[#'passwordInput']", 30000, null, "87912f36-c022-4f39-998f-8d6a19ff5148");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("df5f0e47-553e-4900-9a01-24ea165a5989")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("df5f0e47-553e-4900-9a01-24ea165a5989")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PasswordInput item.
            /// </summary>
            [RepositoryItem("87912f36-c022-4f39-998f-8d6a19ff5148")]
            public virtual Ranorex.InputTag PasswordInput
            {
                get
                {
                    return _passwordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("87912f36-c022-4f39-998f-8d6a19ff5148")]
            public virtual RepoItemInfo PasswordInputInfo
            {
                get
                {
                    return _passwordinputInfo;
                }
            }
        }

        /// <summary>
        /// The KuduServicesAppFolder folder.
        /// </summary>
        [RepositoryFolder("e84fe0dd-7e22-48f7-ad02-07bff40780b9")]
        public partial class KuduServicesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rcc_hubpowershallInfo;

            /// <summary>
            /// Creates a new KuduServices  folder.
            /// </summary>
            public KuduServicesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KuduServices", "/dom[@domain=$AzureDOM]", parentFolder, 30000, null, false, "e84fe0dd-7e22-48f7-ad02-07bff40780b9", "")
            {
                _rcc_hubpowershallInfo = new RepoItemInfo(this, "rcc_hubPowerShall", ".//div[#'KuduExecConsoleV2']/div/div/div[10]/?/?/span", 30000, null, "02ce32dd-e60a-4af8-8c00-70833459f1db");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e84fe0dd-7e22-48f7-ad02-07bff40780b9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e84fe0dd-7e22-48f7-ad02-07bff40780b9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The rcc_hubPowerShall item.
            /// </summary>
            [RepositoryItem("02ce32dd-e60a-4af8-8c00-70833459f1db")]
            public virtual Ranorex.SpanTag rcc_hubPowerShall
            {
                get
                {
                    return _rcc_hubpowershallInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The rcc_hubPowerShall item info.
            /// </summary>
            [RepositoryItemInfo("02ce32dd-e60a-4af8-8c00-70833459f1db")]
            public virtual RepoItemInfo rcc_hubPowerShallInfo
            {
                get
                {
                    return _rcc_hubpowershallInfo;
                }
            }
        }

        /// <summary>
        /// The DiagnosticConsoleAppFolder folder.
        /// </summary>
        [RepositoryFolder("7424d8aa-7302-4ca4-bb9d-70e282c4b92c")]
        public partial class DiagnosticConsoleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cmdInfo;
            RepoItemInfo _netframeworkInfo;
            RepoItemInfo _dllInfo;

            /// <summary>
            /// Creates a new DiagnosticConsole  folder.
            /// </summary>
            public DiagnosticConsoleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DiagnosticConsole", "/dom[@domain='cgst-qcpd-webjobs.scm.azurewebsites.net']", parentFolder, 30000, null, false, "7424d8aa-7302-4ca4-bb9d-70e282c4b92c", "")
            {
                _cmdInfo = new RepoItemInfo(this, "CMD", ".//div[#'KuduExecConsoleV2']/div/div/div[2]/?/?/span", 30000, null, "22aa2717-5e88-45d4-9e78-6bec5f0ba34b");
                _netframeworkInfo = new RepoItemInfo(this, "NetFramework", ".//div[#'KuduExecConsoleV2']//div[@innertext~'^<startup><supportedRuntim']", 30000, null, "82685578-e25b-40fe-9c94-41989b3c76bc");
                _dllInfo = new RepoItemInfo(this, "DLL", ".//div[#'KuduExecConsoleV2']/div/div/div[4]/span[3]", 30000, null, "726f366c-d078-4631-9c47-b56cc04934a1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7424d8aa-7302-4ca4-bb9d-70e282c4b92c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7424d8aa-7302-4ca4-bb9d-70e282c4b92c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CMD item.
            /// </summary>
            [RepositoryItem("22aa2717-5e88-45d4-9e78-6bec5f0ba34b")]
            public virtual Ranorex.SpanTag CMD
            {
                get
                {
                    return _cmdInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CMD item info.
            /// </summary>
            [RepositoryItemInfo("22aa2717-5e88-45d4-9e78-6bec5f0ba34b")]
            public virtual RepoItemInfo CMDInfo
            {
                get
                {
                    return _cmdInfo;
                }
            }

            /// <summary>
            /// The NetFramework item.
            /// </summary>
            [RepositoryItem("82685578-e25b-40fe-9c94-41989b3c76bc")]
            public virtual Ranorex.DivTag NetFramework
            {
                get
                {
                    return _netframeworkInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The NetFramework item info.
            /// </summary>
            [RepositoryItemInfo("82685578-e25b-40fe-9c94-41989b3c76bc")]
            public virtual RepoItemInfo NetFrameworkInfo
            {
                get
                {
                    return _netframeworkInfo;
                }
            }

            /// <summary>
            /// The DLL item.
            /// </summary>
            [RepositoryItem("726f366c-d078-4631-9c47-b56cc04934a1")]
            public virtual Ranorex.SpanTag DLL
            {
                get
                {
                    return _dllInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The DLL item info.
            /// </summary>
            [RepositoryItemInfo("726f366c-d078-4631-9c47-b56cc04934a1")]
            public virtual RepoItemInfo DLLInfo
            {
                get
                {
                    return _dllInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}