///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace eSourcePlatform
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Net_Framework recording.
    /// </summary>
    [TestModule("c63e787d-f0f7-4502-bc2b-55eac038f926", ModuleType.Recording, 1)]
    public partial class Net_Framework : ITestModule
    {
        /// <summary>
        /// Holds an instance of the eSourcePlatformRepository repository.
        /// </summary>
        public static eSourcePlatformRepository repo = eSourcePlatformRepository.Instance;

        static Net_Framework instance = new Net_Framework();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Net_Framework()
        {
            NetFramwork = "";
            Root = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Net_Framework Instance
        {
            get { return instance; }
        }

#region Variables

        string _NetFramwork;

        /// <summary>
        /// Gets or sets the value of variable NetFramwork.
        /// </summary>
        [TestVariable("eb426209-2160-40c2-a589-c6a21387fbe7")]
        public string NetFramwork
        {
            get { return _NetFramwork; }
            set { _NetFramwork = value; }
        }

        string _Root;

        /// <summary>
        /// Gets or sets the value of variable Root.
        /// </summary>
        [TestVariable("4cdcf8ae-6d45-4d39-b096-57635da99994")]
        public string Root
        {
            get { return _Root; }
            set { _Root = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1m.", new RecordItemIndex(0));
            Delay.Duration(60000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DiagnosticConsole.CMD' at Center.", repo.DiagnosticConsole.CMDInfo, new RecordItemIndex(1));
            repo.DiagnosticConsole.CMD.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Root' with focus on 'DiagnosticConsole.CMD'.", repo.DiagnosticConsole.CMDInfo, new RecordItemIndex(2));
            repo.DiagnosticConsole.CMD.PressKeys(Root);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{ENTER}'.", new RecordItemIndex(3));
            Keyboard.Press("{ENTER}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(4));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NetFramwork' with focus on 'DiagnosticConsole.DLL'.", repo.DiagnosticConsole.DLLInfo, new RecordItemIndex(5));
            repo.DiagnosticConsole.DLL.PressKeys(NetFramwork);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{ENTER}'.", new RecordItemIndex(6));
            Keyboard.Press("{ENTER}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
