///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ReportingLayer.PowerBI
{
    public partial class Enter_Username
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        //Enters the login email in the appropriate field.
        public void Enter_Email(RepoItemInfo MicrosoftUsernameField, RepoItemInfo CogstateUsernameField)
        {
        	if (MicrosoftUsernameField.Exists(5000))
        	{
            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo' at Center.", MicrosoftUsernameField);
            	MicrosoftUsernameField.FindAdapter<InputTag>().Click();
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '$CSPUsername' with focus on 'inputtagInfo'.", MicrosoftUsernameField);
            	MicrosoftUsernameField.FindAdapter<InputTag>().PressKeys(CSPUsername);
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'inputtagInfo'.", MicrosoftUsernameField);
            	MicrosoftUsernameField.FindAdapter<InputTag>().PressKeys("{Tab}");        		
        	}
        	else if (CogstateUsernameField.Exists(5000))
        	{
        		//The first line will clear the contents of the Email field if it has been prefilled
        		CogstateUsernameField.FindAdapter<InputTag>().Value = "";
        		Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo' at Center.", CogstateUsernameField);
            	CogstateUsernameField.FindAdapter<InputTag>().Click();
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '$CSPUsername' with focus on 'inputtagInfo'.", CogstateUsernameField);
            	CogstateUsernameField.FindAdapter<InputTag>().PressKeys(CSPUsername);
            	Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'inputtagInfo'.", CogstateUsernameField);
            	CogstateUsernameField.FindAdapter<InputTag>().PressKeys("{Tab}"); 
        	}

        }
    }
}
